Material
size_t Material::m_renderingChannels
Referenced by getChannelMask.
bool Material::m_bActive
Referenced by isEnabled.
std::string Material::m_targetPassName
Referenced by connectPass, getTargetPassName.
ren::RenderQueuePass* Material::m_pTargetPass
Referenced by connectPass.
std::vector<std::shared_ptr<IBindable> > Material::m_bindables
Referenced by Material, accept, getBindables, getBindables.
Material::Material(const size_t channels, const std::string &targetPassName, const bool bStartActive) noexcept
the channels is a bitwise mask (rendering_channel.h) which corresponds to the Rendering channel(s) used for this Material
\function Material || 2024/04/25 13:55
Material::Material(const Material &rhs)
Material & Material::operator=(const Material &rhs)=delete
Material::Material(Material &&rhs) noexcept
Material & Material::operator=(Material &&rhs)=delete
void Material::addBindable(std::shared_ptr< IBindable > pBindable) noexcept
Referenced by CameraFrustum::CameraFrustum, CameraWidget::CameraWidget, Cube::Cube, Line::Line, Plane::Plane, Sphere::Sphere, Terrain::Terrain.
void Material::render(const Mesh &mesh, const size_t channels) const noexcept
void Material::bind(Graphics &gfx) const cond_noex
bool Material::isEnabled() const noexcept
Referenced by ImguiConstantBufferVisitorShowcase::onSetMaterial.
void Material::setEnabled(const bool b) noexcept
Referenced by ImguiConstantBufferVisitorShowcase::onSetMaterial.
void Material::setEnabled(const size_t channels, const bool bEnabled) noexcept
const std::string & Material::getTargetPassName() const noexcept
Referenced by ImguiConstantBufferVisitorShowcase::onSetMaterial.
void Material::setMesh(const Mesh &parent) noexcept
void Material::accept(IImGuiConstantBufferVisitor &ev)
void Material::connectPass(ren::Renderer &r)
std::vector< std::shared_ptr< IBindable > > & Material::getBindables()
const std::vector< std::shared_ptr< IBindable > > & Material::getBindables() const noexcept
size_t Material::getChannelMask() const noexcept