ren::IBindablePass
std::vector<std::shared_ptr<IBindable> > ren::IBindablePass::m_bindables
Referenced by addBindableBinderUsingContainerIndex.
std::shared_ptr<IRenderTargetView> ren::IBindablePass::m_pRtv
Referenced by ren::DepthReversedPass::DepthReversedPass, ren::HorizontalBlurPass::HorizontalBlurPass, ren::OpaquePass::OpaquePass, ren::Pass2D::Pass2D, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, ren::VerticalBlurPass::VerticalBlurPass, ren::WireframePass::WireframePass, validate.
std::shared_ptr<IDepthStencilView> ren::IBindablePass::m_pDsv
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, ren::DepthReversedPass::DepthReversedPass, ren::OpaquePass::OpaquePass, ren::Pass2D::Pass2D, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, ren::VerticalBlurPass::VerticalBlurPass, ren::WireframePass::WireframePass, validate.
ren::IBindablePass::IBindablePass(const std::string &name, const std::vector< std::shared_ptr< IBindable > > &bindables={})
void ren::IBindablePass::addBindable(std::shared_ptr< IBindable > bindable) noexcept
add Bindables that will be shared by all meshes in this Pass
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, ren::BlurPass::BlurPass, ren::DepthReversedPass::DepthReversedPass, ren::HorizontalBlurPass::HorizontalBlurPass, ren::NegativePass::NegativePass, ren::OpaquePass::OpaquePass, ren::Pass2D::Pass2D, ren::PassThrough::PassThrough, ren::ShadowPass::ShadowPass, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, ren::VerticalBlurPass::VerticalBlurPass, ren::WireframePass::WireframePass.
void ren::IBindablePass::bind(Graphics &gfx) const cond_noex
bind RTV or DSV and other bindables shared by all Pass objects
call this function as the first thing you do on a child class's run function
Referenced by ren::RenderQueuePass::run.
void ren::IBindablePass::validate() override
validate binders are linked to their linkers
validation occurs only once (ctor) for every Pass
void ren::IBindablePass::addBindableBinderUsingContainerIndex(const std::string &binderName)
Referenced by ren::HorizontalBlurPass::HorizontalBlurPass, ren::OpaquePass::OpaquePass, ren::VerticalBlurPass::VerticalBlurPass.