PerlinNoise
std::vector<int> PerlinNoise::m_permutationVec
Referenced by PerlinNoise, noise.
PerlinNoise::PerlinNoise(unsigned int seed=0)
generate a new permutation vector based on the value of seed
double PerlinNoise::noise(double x, double y, double z)
get a noise value, for 2D images z can have any value
Referenced by BmpLoader::applyPerlinNoise.
double PerlinNoise::fade(const double t)
Referenced by noise.
double PerlinNoise::grad(const int hash, const double x, const double y, const double z)
Referenced by noise.