ren::Renderer3d
KernelType
int ren::Renderer3d::s_maxRadius
Referenced by recreate.
float ren::Renderer3d::s_maxSigma
unsigned ren::Renderer3d::s_fullscreenRezReductFactor
Referenced by recreate.
int ren::Renderer3d::m_radius
Referenced by recreate.
float ren::Renderer3d::m_sigma
Referenced by recreate.
std::shared_ptr<PixelShaderConstantBufferEx> ren::Renderer3d::m_blurKernel
Referenced by recreate.
std::shared_ptr<PixelShaderConstantBufferEx> ren::Renderer3d::m_blurDirection
Referenced by recreate.
KernelType ren::Renderer3d::m_kernelType
ren::Renderer3d::Renderer3d(Graphics &gfx, const bool bDrawToOffscreen, const int radius, const float sigma, const KernelType kernelType=Gauss)
void ren::Renderer3d::recreate(Graphics &gfx) override
Referenced by Renderer3d.
void ren::Renderer3d::displayImguiWidgets(Graphics &gfx) noexcept
Referenced by Sandbox3d::test.
void ren::Renderer3d::dumpShadowMap(Graphics &gfx, const std::string &path)
Referenced by Sandbox3d::checkInput, dumpShadowMap.
void ren::Renderer3d::dumpShadowCubeMap(Graphics &gfx, const std::string &path)
Referenced by dumpShadowCubeMap.
void ren::Renderer3d::setActiveCamera(const Camera &cam)
binds active camera to all Passes that need it
Referenced by Sandbox3d::update.
void ren::Renderer3d::bindShadowCastingLights(Graphics &gfx, const std::vector< ILightSource * > &shadowCastingLights)
Referenced by Sandbox3d::render.
void ren::Renderer3d::showShadowDumpImguiWindow(Graphics &gfx) noexcept
void ren::Renderer3d::showGaussianBlurImguiWindow(Graphics &gfx) noexcept
void ren::Renderer3d::showDisplayMode(Graphics &gfx) noexcept
void ren::Renderer3d::setKernelGauss(const int radius, const float sigma) cond_noex
Referenced by recreate.
void ren::Renderer3d::setKernelBox(const int radius) cond_noex