KeyTimer
using KeyTimer< Resolution >::TClock = std::conditional_t<std::chrono::high_resolution_clock::is_steady, std::chrono::high_resolution_clock, std::chrono::steady_clock>
TClock::time_point KeyTimer< Resolution >::m_start
Referenced by KeyTimer< Resolution >::getMilliSecondsFromStart, KeyTimer< Resolution >::getSecondsFromStart, KeyTimer< Resolution >::reset, KeyTimer< Resolution >::restart, KeyTimer< Resolution >::start.
TClock::time_point KeyTimer< Resolution >::m_last
Referenced by KeyTimer< Resolution >::getTimeElapsed, KeyTimer< Resolution >::getTimeElapsedSecs, KeyTimer< Resolution >::lap, KeyTimer< Resolution >::peekTimeElapsed, KeyTimer< Resolution >::start.
size_t KeyTimer< Resolution >::m_duration
Referenced by KeyTimer< Resolution >::getMilliSecondsFromStart, KeyTimer< Resolution >::restart, KeyTimer< Resolution >::start.
KeyTimer< Resolution >::KeyTimer(bool bStart=false) noexcept
KeyTimer< Resolution >::~KeyTimer() noexcept
void KeyTimer< Resolution >::start() noexcept
Referenced by Game< T >::Game, Graphics::Graphics, KeyTimer< Resolution >::KeyTimer, Arkanoid::loop, PerfLog::start.
void KeyTimer< Resolution >::restart() noexcept
void KeyTimer< Resolution >::reset() noexcept
size_t KeyTimer< Resolution >::getMilliSecondsFromStart() noexcept
returns the duration between m_start and now in milliseconds
Referenced by KeyTimer< Resolution >::~KeyTimer.
float KeyTimer< Resolution >::getSecondsFromStart() noexcept
returns the duration between m_start and now in seconds
float KeyTimer< Resolution >::getTimeElapsed() noexcept
marks a lap, which marks the current time
returns duration in targeted Time Resolution between successive calls of the function and
Referenced by PerfLog::start.
float KeyTimer< Resolution >::getTimeElapsedSecs() noexcept
marks a lap
returns duration in seconds
float KeyTimer< Resolution >::peekTimeElapsed() const noexcept
returns duration between the last call of getTimeElapsed() and now
float KeyTimer< Resolution >::lap() noexcept
works like getTimeElapsed/getTimeElapsedSecs but may be more performant
Referenced by Arkanoid::calcDt, PerfLog::lap, Sandbox3d::loop.
static void KeyTimer< Resolution >::sleepFor(const float t)
delays execution of this_thread for the amount of time specified (in milliseconds, or microseconds)
Referenced by KeyTimer< Resolution >::sleepFor, KeyTimer< Resolution >::sleepFor, KeyTimer< Resolution >::sleepFor.
static void KeyTimer< Resolution >::sleepFor(const int t)
static void KeyTimer< Resolution >::sleepFor(const uint64_t t)
static void KeyTimer< Resolution >::sleepFor(const std::chrono::milliseconds &t)
static void KeyTimer< Resolution >::sleepFor(const std::chrono::microseconds &t)