ver::VertexInputLayout
ILEementType
std::vector<ILElement> ver::VertexInputLayout::m_vertexLayoutElements
Referenced by calcSignature, fetch, getD3DInputElementDescs, getElementCount, getSizeInBytes.
static constexpr auto ver::VertexInputLayout::bridge(const VertexInputLayout::ILEementType type, Args &&... args) cond_noex
use bridge() at runtime to get information about an element's properties
Referenced by ver::VBuffer::VBuffer, ver::VertexInputLayout::ILElement::getD3dDesc, ver::VertexInputLayout::ILElement::getElementTypeSize, ver::VertexInputLayout::ILElement::getTag, ver::VBElementView::setElementByIndex.
const ILElement & ver::VertexInputLayout::fetch() const cond_noex
Referenced by ver::VBElementView::getElement.
const VertexInputLayout::ILElement & ver::VertexInputLayout::getElementByIndex(const size_t i) const cond_noex
Referenced by ver::VBuffer::VBuffer, ver::VBElementView::setElementByIndex.
VertexInputLayout & ver::VertexInputLayout::add(const ILEementType type) cond_noex
Referenced by ren::Pass2D::Pass2D, Geometry::makeCameraFrustum, Geometry::makeCameraWidget, Geometry::makeCube, Geometry::makeCubeIndependentFacesTextured, Geometry::makeLine, Geometry::makePlanarGrid, Geometry::makePlanarGridTextured, Geometry::makePlanarGridTexturedFromHeighmap, Geometry::makeSphereTesselated, testDynamicMeshLoading, testDynamicVertex.
size_t ver::VertexInputLayout::getSizeInBytes() const cond_noex
Referenced by ver::VBuffer::back, ver::VBuffer::emplaceVertex, ver::VBuffer::getVertexCount, ver::VBuffer::resize.
size_t ver::VertexInputLayout::getElementCount() const noexcept
Referenced by ver::VBuffer::VBuffer, ver::VBuffer::emplaceVertex, getD3DInputElementDescs.
std::vector< D3D11_INPUT_ELEMENT_DESC > ver::VertexInputLayout::getD3DInputElementDescs() const cond_noex
Referenced by InputLayout::InputLayout.
std::string ver::VertexInputLayout::calcSignature() const cond_noex
Referenced by InputLayout::calcUid, InputLayout::getUid.
bool ver::VertexInputLayout::hasType(const ILEementType &type) const noexcept