con::CBElement
friend class RawLayout
friend struct ExtraData
std::optional<size_t> con::CBElement::m_offset
each element stores its own offset. this makes lookup to find its position in the byte buffer fast.
Special handling is required for situations where arrays are involved
Referenced by commitArray, commitStruct, getOffsetBegin, getOffsetEnd.
ElementType con::CBElement::m_type
Referenced by calcSignature, fetch, getOffsetEnd, isValid, T.
std::unique_ptr<IExtraData> con::CBElement::m_pExtraData
std::string con::CBElement::calcSignature() const cond_noex
get a string signature for this element (recursive); when called on the root
element of a layout tree, generates a uniquely-identifying string for the layout we can use that signature to store a codex of layouts and to share layouts
bool con::CBElement::isValid() const noexcept
Check if element is "real".
Referenced by con::CBElementConstView::isValid, con::CBElementView::isValid.
std::pair< size_t, const CBElement * > con::CBElement::calculateArrayIndexingOffset(const size_t offset, const size_t index) const cond_noex
calculate array indexing offset - tricky
CBElement & con::CBElement::operator[](const std::string &key) cond_noex
[] only works for Structs; access element (child node in tree) by name
const CBElement & con::CBElement::operator[](const std::string &key) const cond_noex
CBElement & con::CBElement::T() cond_noex
T() only works for Arrays; gets the array class layout object.
needed to further configure an array's class
Referenced by T.
const CBElement & con::CBElement::T() const cond_noex
size_t con::CBElement::getOffsetBegin() const cond_noex
offset based- functions only work after finalization!
Referenced by getSizeInBytes.
size_t con::CBElement::getOffsetEnd() const cond_noex
Referenced by commitArray, getSizeInBytes.
size_t con::CBElement::getSizeInBytes() const cond_noex
get size in bytes derived from offsets
Referenced by IConstantBufferEx::IConstantBufferEx.
CBElement & con::CBElement::add(const ElementType addedType, const std::string &name) cond_noex
only works for Structs; add CBElement to struct
Referenced by add, con::RawLayout::add.
CBElement & con::CBElement::add(const std::string &key) cond_noex
CBElement & con::CBElement::set(const ElementType addedType, const size_t size) cond_noex
only works for Arrays; set the class and the # of elements
Referenced by set.
CBElement & con::CBElement::set(const size_t size) cond_noex
const size_t con::CBElement::fetch() const cond_noex
returns offset of leaf types for read/write purposes w/ typecheck in Debug
Referenced by con::CBElementConstView::operator const T &, con::CBElementView::operator T&.
con::CBElement::CBElement() noexcept=default
construct an empty layout element
con::CBElement::CBElement(const ElementType typeIn) cond_noex
const size_t con::CBElement::commit(const size_t offsetIn) cond_noex
sets all offsets for element and subelements, prepending padding when necessary
returns offset directly after this element
std::string con::CBElement::getSignatureForStruct() const cond_noex
implementations for GetSignature for aggregate types
Referenced by calcSignature.
std::string con::CBElement::calcSignatureForArray() const cond_noex
Referenced by calcSignature.
const size_t con::CBElement::commitStruct(const size_t offsetIn)
implementations for commit for aggregate types
const size_t con::CBElement::commitArray(const size_t offsetIn)
static CBElement & con::CBElement::getEmptyElement() noexcept
returns singleton instance of empty layout element
const size_t con::CBElement::advanceToBoundary(const size_t offset) noexcept
returns the value of offset bumped up to the next 16-byte boundary (if not already on one)
Referenced by commitArray, commitStruct, getOffsetEnd.
bool con::CBElement::doesCrossBoundary(const size_t offset, const size_t size) noexcept
return true if a memory block crosses a boundary
const size_t con::CBElement::advanceIfCrossesBoundary(const size_t offset, const size_t size) noexcept
advance an offset to next boundary if block crosses a boundary
bool con::CBElement::validateMemberName(const std::string &name) noexcept
check string for validity as a struct key