BindableRegistry
std::unordered_map<std::string, std::shared_ptr<IBindable> > BindableRegistry::m_bindableMap
Referenced by fetch_impl.
static std::shared_ptr< T > BindableRegistry::fetch(Graphics &gfx, TArgs &&... args) cond_noex
Referenced by BlendState::fetch, CubeTexture::fetch, DepthStencilState::fetch, IndexBuffer::fetch, InputLayout::fetch, PixelShader::fetch, PixelShaderConstantBuffer< CB >::fetch, PixelShaderConstantBuffer< CB >::fetch, PixelShaderNull::fetch, PrimitiveTopology::fetch, RasterizerState::fetch, Texture::fetch, TextureSamplerState::fetch, VertexBuffer::fetch, VertexShader::fetch, VertexShaderConstantBuffer< CB >::fetch, VertexShaderConstantBuffer< CB >::fetch, Viewport::fetch.
static std::size_t BindableRegistry::getInstanceCount()
static std::size_t BindableRegistry::getGarbageCount()
static void BindableRegistry::garbageCollect()
std::shared_ptr< T > BindableRegistry::fetch_impl(Graphics &gfx, TArgs &&... args) cond_noex
Referenced by fetch.
static BindableRegistry & BindableRegistry::getInstance()
Referenced by fetch, garbageCollect, getGarbageCount, getInstanceCount.