MaterialLoader
ver::VertexInputLayout MaterialLoader::m_vertexLayout
std::string MaterialLoader::m_modelPath
std::string MaterialLoader::m_name
std::vector<Material> MaterialLoader::m_materials
Referenced by getMaterial.
MaterialLoader::MaterialLoader(Graphics &gfx, const aiMaterial &aimaterial, const std::filesystem::path &modelPath) cond_noex
std::shared_ptr< VertexBuffer > MaterialLoader::makeVertexBuffer(Graphics &gfx, const aiMesh &aimesh, float scale=1.0f) const cond_noex
Referenced by Mesh::Mesh.
std::shared_ptr< IndexBuffer > MaterialLoader::makeIndexBuffer(Graphics &gfx, const aiMesh &aimesh) const cond_noex
Referenced by Mesh::Mesh.
std::vector< Material > MaterialLoader::getMaterial() const noexcept
Referenced by Mesh::Mesh.
std::string MaterialLoader::calcMeshTag(const aiMesh &mesh) const noexcept
ver::VBuffer MaterialLoader::makeVertexBuffer_impl(const aiMesh &aimesh) const noexcept
std::vector< unsigned > MaterialLoader::makeIndexBuffer_impl(const aiMesh &aimesh) const noexcept