KeyConsole
LogCategory
const char* KeyConsole::s_currentVersion
const char* KeyConsole::s_defaultConsoleTitle
KeyConsole* KeyConsole::s_pInstance
Referenced by getInstance, resetInstance.
FILE* KeyConsole::m_fp
Referenced by closeConsole, error, log, print, read.
DWORD KeyConsole::m_stdDevice
Referenced by error, getConsoleModeStr, log, print, read.
FILE* KeyConsole::m_hMode
Referenced by closeConsole, error, getConsoleMode, log, print, read.
HANDLE KeyConsole::m_hConsole
Referenced by error, getHandle, log, print, read, setColor, setCurcorPos, setDefaultColor, setFont.
WORD KeyConsole::m_consoleAttributesDefault
Referenced by getConsoleDefaultTextAttributes, getConsoleTextAttributes, setDefaultColor.
WORD KeyConsole::m_consoleAttributes
Referenced by setColor.
KeyConsole::KeyConsole(const std::string &fontName="Lucida Console")
Referenced by getInstance.
DWORD KeyConsole::getFontFamily(const HANDLE h)
Referenced by getConsoleInfo.
void KeyConsole::getConsoleInfo(const HANDLE h)
Referenced by setFont.
bool KeyConsole::setDefaultColor()
Referenced by KeyConsole.
KeyConsole & KeyConsole::getInstance() noexcept
Referenced by DxgiInfoQueue::DxgiInfoQueue, MousePicker::MousePicker, Window::WindowClass::WindowClass, KeyTimer< Resolution >::~KeyTimer, assertPrint, Window::dialogProc, finally, firstly, KeyTimer< Resolution >::getMilliSecondsFromStart, KeyTimer< Resolution >::getSecondsFromStart, Graphics::Adapter::getVRamDetails, installSigabrtHandler, installSigfpeHandler, installSigillHandler, installSigintHandler, installSigsegvHandler, installSigtermHandler, Graphics::interrogateDirectxFeatures, Sandbox3d::loop, parseCommandLineArguments, Graphics::profile, Window::saveClipboardTextAsVar, Game< T >::setState, Window::splashWindowProc, Window::splashWindowTimerProc, util::terminateDetachedThreads, TextureProcessor::validateNormalMap, Window::windowProc, Window::windowProc_impl2d, Window::windowProc_impl3d.
void KeyConsole::resetInstance()
you must call this manually prior to program exit to avoid memory leaks
Referenced by finally.
KeyConsole::~KeyConsole()
DWORD KeyConsole::print(const std::string &msg)
print to stdout
Referenced by KeyConsole, MousePicker::MousePicker, Graphics::Adapter::getVRamDetails, Sandbox3d::loop, parseCommandLineArguments, Graphics::profile, Window::saveClipboardTextAsVar, Game< T >::setState, util::terminateDetachedThreads.
DWORD KeyConsole::log(const std::string &msg, LogCategory cat=None)
Referenced by DxgiInfoQueue::DxgiInfoQueue, KeyTimer< Resolution >::~KeyTimer, assertPrint, finally, KeyTimer< Resolution >::getMilliSecondsFromStart, KeyTimer< Resolution >::getSecondsFromStart, installSigabrtHandler, installSigfpeHandler, installSigillHandler, installSigintHandler, installSigsegvHandler, installSigtermHandler.
DWORD KeyConsole::error(const std::string &msg)
print to stderr
std::string KeyConsole::read(const uint32_t maxChars=1024u)
read from stdin, returns the string
void KeyConsole::setTitle(const std::string &title) const
Referenced by getWindowHandle.
bool KeyConsole::closeConsole()
Referenced by ~KeyConsole.
const HWND KeyConsole::getWindowHandle() const noexcept
int KeyConsole::getConsoleMode() const noexcept
std::string KeyConsole::getConsoleModeStr() const noexcept
Referenced by KeyConsole.
const HANDLE KeyConsole::getHandle() const noexcept
get current console's Code Page. for a list of code pages check link: https://docs.microsoft.com/el-gr/windows/desktop/Intl/code-page-identifiers
std::string KeyConsole::getTitle() const noexcept
uint32_t KeyConsole::getConsoleCodePage() const noexcept
int32_t KeyConsole::setConsoleCodePage(const uint32_t cp)
void KeyConsole::setFont(const std::string &fontName)
Referenced by KeyConsole.
int32_t KeyConsole::setCurcorPos(const _COORD xy={0, 0})
bool KeyConsole::setColor(const WORD attributes=FOREGROUND_RED|BACKGROUND_RED|BACKGROUND_GREEN)
WORD KeyConsole::getConsoleTextAttributes() const noexcept
WORD KeyConsole::getConsoleDefaultTextAttributes() const noexcept
void KeyConsole::show() const
void KeyConsole::hide() const
bool KeyConsole::operator==(const KeyConsole &rhs) const noexcept
bool KeyConsole::operator!=(const KeyConsole &rhs) const noexcept
bool KeyConsole::operator==(const KeyConsole *rhs) const noexcept
bool KeyConsole::operator!=(const KeyConsole *rhs) const noexcept