ren::ILinker
std::string ren::ILinker::m_name
Referenced by getName.
ren::ILinker::ILinker(const std::string &name)
virtual ren::ILinker::~ILinker() noexcept=default
const std::string & ren::ILinker::getName() const noexcept
std::shared_ptr< IBindable > ren::ILinker::getBindable()
Referenced by ren::BindableBinder< T >::link, ren::ContainerBindableBinder< T >::link.
std::shared_ptr< IRenderSurface > ren::ILinker::getRenderSurface()
Referenced by ren::RenderSurfaceBinder< T >::link.