Keyboard
friend class Window
unsigned int Keyboard::s_nKeys
unsigned int Keyboard::s_maxBufferSize
bool Keyboard::m_bAutorepeat
Referenced by disableAutorepeat, enableAutorepeat, isAutorepeatEnabled.
std::bitset<s_nKeys> Keyboard::m_keyStates
Referenced by clearKeyStates.
std::queue<Keyboard::Event> Keyboard::m_eventQueue
Referenced by flushEventQueue, isEventQueueEmpty, readEventQueue.
std::queue<char> Keyboard::m_charBuffer
Referenced by flushCharBuffer, isCharBufferEmpty, readCharBuffer.
Keyboard::Keyboard()=default
void Keyboard::onKeyPressed(unsigned char keycode) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Keyboard::onKeyReleased(unsigned char keycode) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Keyboard::onChar(char c) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Keyboard::clearKeyStates() noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Keyboard::trimBuffer(std::queue< T > &buf) noexcept
check whether the provided buffer needs trimming
Keyboard::~Keyboard() noexcept=default
Keyboard::Keyboard(Keyboard &&rhs) noexcept
Keyboard & Keyboard::operator=(Keyboard &&rhs) noexcept
bool Keyboard::isKeyPressed(unsigned char keycode) const noexcept
std::optional< Keyboard::Event > Keyboard::readEventQueue() noexcept
read event from the queue if any
bool Keyboard::isEventQueueEmpty() const noexcept
void Keyboard::flushEventQueue() noexcept
clear events
Referenced by flushAll.
std::optional< char > Keyboard::readCharBuffer() noexcept
bool Keyboard::isCharBufferEmpty() const noexcept
void Keyboard::flushCharBuffer() noexcept
Referenced by flushAll.
void Keyboard::flushAll() noexcept
void Keyboard::enableAutorepeat() noexcept
void Keyboard::disableAutorepeat() noexcept
bool Keyboard::isAutorepeatEnabled() const noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.