Viewport
D3D11_VIEWPORT Viewport::m_viewport
Referenced by Viewport, getHeight, getUid, getViewport, getWidth.
Viewport::Viewport(Graphics &gfx)
Referenced by calcUid.
Viewport::Viewport(Graphics &gfx, const float width, const float height)
void Viewport::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
D3D11_VIEWPORT Viewport::getViewport() const noexcept
float Viewport::getWidth() const noexcept
float Viewport::getHeight() const noexcept
std::string Viewport::getUid() const noexcept override
std::shared_ptr< Viewport > Viewport::fetch(Graphics &gfx, const float width, const float height)
Referenced by IDepthStencilView::bindRenderSurface, IRenderTargetView::bindRenderSurface.
std::string Viewport::calcUid(const float width, const float height)
Referenced by getUid.