Mouse
friend class Window
unsigned int Mouse::s_maxBufferSize
Referenced by trimEventQueue, trimRawInputBuffer.
int Mouse::m_x
Referenced by getPosition, getX.
int Mouse::m_y
Referenced by getPosition, getY.
bool Mouse::m_bLmbPressed
Referenced by isLmbPressed.
bool Mouse::m_bRmbPressed
Referenced by isRmbPressed.
bool Mouse::m_bMmbPressed
Referenced by isMmbPressed.
bool Mouse::m_bInWindow
Referenced by isInWindow, onMouseEnterWindow, onMouseLeaveWindow.
int Mouse::m_wheelDelta
bool Mouse::m_bRawEnabled
Referenced by disableRawInput, enableRawInput, isRawInputEnabled.
std::queue<Event> Mouse::m_eventQueue
Referenced by flushEvents, isQueueEmpty, onMouseEnterWindow, onMouseLeaveWindow, readEventQueue, trimEventQueue.
std::queue<RawDelta> Mouse::m_rawDeltaBuffer
Referenced by readRawDeltaBuffer, trimRawInputBuffer.
Mouse::Mouse()=default
void Mouse::onMouseMove(const int newx, const int newy) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onMouseEnterWindow() noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onMouseLeaveWindow() noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onLmbPressed(const int x, const int y) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onLmbReleased(const int x, const int y) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onRmbPressed(const int x, const int y) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onRmbReleased(const int x, const int y) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onMmbPressed(const int x, const int y) noexcept
void Mouse::onMmbReleased(const int x, const int y) noexcept
void Mouse::onWheelDelta(const int x, const int y, const int delta) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::onWheelUp(const int x, const int y) noexcept
void Mouse::onWheelDown(const int x, const int y) noexcept
void Mouse::onRawDelta(const int dx, const int dy) noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
void Mouse::trimEventQueue() noexcept
Referenced by onMouseEnterWindow, onMouseLeaveWindow.
void Mouse::trimRawInputBuffer() noexcept
Mouse::~Mouse() noexcept=default
Mouse::Mouse(Mouse &&rhs) noexcept
Mouse & Mouse::operator=(Mouse &&rhs) noexcept
std::pair< int, int > Mouse::getPosition() const noexcept
int Mouse::getX() const noexcept
int Mouse::getY() const noexcept
bool Mouse::isInWindow() const noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
bool Mouse::isLmbPressed() const noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
bool Mouse::isRmbPressed() const noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.
bool Mouse::isMmbPressed() const noexcept
std::optional< Mouse::RawDelta > Mouse::readRawDeltaBuffer() noexcept
std::optional< Mouse::Event > Mouse::readEventQueue() noexcept
bool Mouse::isQueueEmpty() const noexcept
void Mouse::flushEvents() noexcept
void Mouse::enableRawInput() noexcept
Referenced by Game< T >::setState.
void Mouse::disableRawInput() noexcept
Referenced by Game< T >::setState.
bool Mouse::isRawInputEnabled() const noexcept
Referenced by Window::windowProc_impl2d, Window::windowProc_impl3d.