IndexBuffer
std::string IndexBuffer::m_tag
Referenced by getUid.
unsigned IndexBuffer::m_count
Referenced by IndexBuffer, getIndexCount.
Microsoft::WRL::ComPtr<ID3D11Buffer> IndexBuffer::m_pIndexBuffer
Referenced by IndexBuffer.
IndexBuffer::IndexBuffer(Graphics &gfx, const std::vector< unsigned > &indices)
Referenced by calcUid.
IndexBuffer::IndexBuffer(Graphics &gfx, const std::string &tag, const std::vector< unsigned > &indices)
void IndexBuffer::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
unsigned IndexBuffer::getIndexCount() const noexcept
std::string IndexBuffer::getUid() const noexcept override
std::shared_ptr< IndexBuffer > IndexBuffer::fetch(Graphics &gfx, const std::string &tag, const std::vector< unsigned > &indices)
Referenced by CameraFrustum::CameraFrustum, CameraWidget::CameraWidget, Cube::Cube, Line::Line, Plane::Plane, ren::SkyPass::SkyPass, Sphere::Sphere, Terrain::Terrain, MaterialLoader::makeIndexBuffer, testDynamicVertex.
static std::string IndexBuffer::calcUid(const std::string &tag, TArgsIgnored &&...)
Referenced by getUid.