VertexBuffer
unsigned VertexBuffer::m_stride
Referenced by VertexBuffer.
std::string VertexBuffer::m_tag
Referenced by getUid.
ver::VertexInputLayout VertexBuffer::m_vertexLayout
Referenced by getLayout.
Microsoft::WRL::ComPtr<ID3D11Buffer> VertexBuffer::m_pVertexBuffer
Referenced by VertexBuffer.
VertexBuffer::VertexBuffer(Graphics &gfx, const ver::VBuffer &vb)
Referenced by calcUid.
VertexBuffer::VertexBuffer(Graphics &gfx, const std::string &tag, const ver::VBuffer &vb)
void VertexBuffer::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
const ver::VertexInputLayout & VertexBuffer::getLayout() const noexcept
std::string VertexBuffer::getUid() const noexcept override
std::shared_ptr< VertexBuffer > VertexBuffer::fetch(Graphics &gfx, const std::string &tag, const ver::VBuffer &vb)
Referenced by CameraWidget::CameraWidget, Cube::Cube, Line::Line, Plane::Plane, ren::SkyPass::SkyPass, Sphere::Sphere, Terrain::Terrain, MaterialLoader::makeVertexBuffer, testDynamicVertex.
static std::string VertexBuffer::calcUid(const std::string &tag, TArgsIgnored &&...)
Referenced by getUid.