PixelShaderNull
PixelShaderNull::PixelShaderNull(Graphics &gfx)
Referenced by calcUid.
void PixelShaderNull::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
std::string PixelShaderNull::getUid() const noexcept override
std::shared_ptr< PixelShaderNull > PixelShaderNull::fetch(Graphics &gfx)
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, ren::ShadowPass::ShadowPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass.
std::string PixelShaderNull::calcUid()
Referenced by getUid.