con::RawLayout
friend class LayoutMap
con::RawLayout::RawLayout() noexcept
Referenced by clear, cookLayout.
CBElement & con::RawLayout::operator[](const std::string &key) cond_noex
CBElement & con::RawLayout::add(const std::string &key) cond_noex
Referenced by Cube::Cube, Line::Line, Plane::Plane, Sphere::Sphere, Terrain::Terrain, TransformScaleVSCB::calcCbLayout, ren::Renderer3d::recreate, testDynamicConstant.
void con::RawLayout::clear() noexcept
reset this object with an empty struct at its root
std::shared_ptr< CBElement > con::RawLayout::cookLayout() noexcept
cook/commit the layout and then relinquish (by yielding the root layout element)