VertexShaderConstantBuffer
void VertexShaderConstantBuffer< CB >::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
std::string VertexShaderConstantBuffer< CB >::getUid() const noexcept override
static std::shared_ptr< VertexShaderConstantBuffer > VertexShaderConstantBuffer< CB >::fetch(Graphics &gfx, const CB &cb, const unsigned slot)
static std::shared_ptr< VertexShaderConstantBuffer > VertexShaderConstantBuffer< CB >::fetch(Graphics &gfx, const unsigned slot)
static std::string VertexShaderConstantBuffer< CB >::calcUid(const CB &cb, const unsigned slot)
Referenced by VertexShaderConstantBuffer< CB >::calcUid, VertexShaderConstantBuffer< CB >::getUid.
static std::string VertexShaderConstantBuffer< CB >::calcUid(const unsigned slot)
static VertexShaderConstantBuffer< CB > VertexShaderConstantBuffer< CB >::makeCopy(ID3D11Buffer *srcBuf, const unsigned slot)
Referenced by TransformVSCB::TransformVSCB.