ver::VBuffer
std::vector<char> ver::VBuffer::m_data
Referenced by back, front, getSizeInBytes.
VertexInputLayout ver::VBuffer::m_vertexLayout
Referenced by VBuffer, back, front, getLayout, getVertexCount.
ver::VBuffer::VBuffer(VertexInputLayout layout, const size_t vertexCount=0u) cond_noex
ver::VBuffer::VBuffer(VertexInputLayout layout, const aiMesh &mesh)
const char * ver::VBuffer::data() const cond_noex
Referenced by VertexBuffer::VertexBuffer.
const VertexInputLayout & ver::VBuffer::getLayout() const noexcept
Referenced by ren::SkyPass::SkyPass.
void ver::VBuffer::resize(const size_t newVertexCount) cond_noex
Referenced by VBuffer.
size_t ver::VBuffer::getVertexCount() const cond_noex
Referenced by TriangleMesh::TriangleMesh, Mesh::createAabb, Geometry::makeSphereTesselated, TriangleMesh::transform.
size_t ver::VBuffer::getSizeInBytes() const cond_noex
Referenced by VertexBuffer::VertexBuffer, back, getVertexCount.
void ver::VBuffer::emplaceVertex(TArgs &&... args) cond_noex
Referenced by Geometry::makeCameraWidget.
VBElementView ver::VBuffer::back() cond_noex
Referenced by back.
VBElementConstView ver::VBuffer::back() const cond_noex
VBElementView ver::VBuffer::front() cond_noex
Referenced by front.
VBElementConstView ver::VBuffer::front() const cond_noex
VBElementView ver::VBuffer::operator[](const size_t i) cond_noex
VBElementConstView ver::VBuffer::operator[](const size_t i) const cond_noex