ren::Renderer
bool ren::Renderer::m_bValidatedPasses
Referenced by addPass, recreate, reset, validateBindersLinkage.
std::vector<std::unique_ptr<IPass> > ren::Renderer::m_passes
Referenced by addPass, getRenderQueuePass, linkGlobalBinders, linkPassBinders, recreate, reset, validateBindersLinkage.
std::vector<std::unique_ptr<IBinder> > ren::Renderer::m_globalBinders
Referenced by addGlobalBinder, linkGlobalBinders, recreate, setupGlobalBinderTarget.
std::vector<std::unique_ptr<ILinker> > ren::Renderer::m_globalLinkers
Referenced by addGlobalLinker, linkPassBinders, recreate.
bool ren::Renderer::m_bUsesOffscreen
Referenced by isUsingOffscreenRendering, ren::Renderer3d::recreate, recreate, reset.
std::unique_ptr<IPass> ren::Renderer::m_pFinalPostProcessPass
Referenced by ren::Renderer3d::recreate, recreate, reset.
std::shared_ptr<IRenderTargetView> ren::Renderer::m_pRtv
Referenced by recreate.
std::shared_ptr<IDepthStencilView> ren::Renderer::m_pDsv
Referenced by recreate.
ren::Renderer::Renderer(Graphics &gfx, const bool drawToOffscreen)
ren::Renderer::~Renderer() noexcept
void ren::Renderer::run(Graphics &gfx) cond_noex
void ren::Renderer::recreate(Graphics &gfx)
Referenced by Renderer, ren::Renderer2d::recreate, ren::Renderer3d::recreate.
void ren::Renderer::reset() noexcept
RenderQueuePass & ren::Renderer::getRenderQueuePass(const std::string &name)
Referenced by Material::connectPass.
bool ren::Renderer::isUsingOffscreenRendering() const noexcept
void ren::Renderer::addGlobalLinker(std::unique_ptr< ILinker > pLinker)
Referenced by ren::Renderer3d::recreate, recreate.
void ren::Renderer::addGlobalBinder(std::unique_ptr< IBinder > pBinder)
Referenced by recreate.
void ren::Renderer::addPass(std::unique_ptr< IPass > pPass)
Referenced by ren::Renderer2d::recreate, ren::Renderer3d::recreate, recreate.
void ren::Renderer::setupGlobalBinderTarget(const std::string &globalBinderName, const std::string &passName, const std::string &linkerName)
Referenced by ren::Renderer2d::recreate, ren::Renderer3d::recreate.
void ren::Renderer::linkGlobalBinders()
Referenced by ren::Renderer2d::recreate, ren::Renderer3d::recreate.
IPass & ren::Renderer::getPass(const std::string &name)
Referenced by ren::Renderer3d::dumpShadowCubeMap, ren::Renderer3d::dumpShadowMap.
void ren::Renderer::validateBindersLinkage()
Referenced by linkGlobalBinders.
void ren::Renderer::linkPassBinders(IPass &pass)
links pass's binders to their linkers
Referenced by addPass.
void ren::Renderer::offscreenToBackBufferSwap(Graphics &gfx)
If there's a final post process pass (Pass that renders directly to the Back Buffer) then swap the render targets, ie.
bind 1. Back Buffer RTV as output and 2. Offscreen RTV as input