con::CBuffer
std::shared_ptr<CBElement> con::CBuffer::m_pLayoutRoot
Referenced by CBuffer, ~CBuffer, getRootElement, shareLayoutRoot.
std::vector<char> con::CBuffer::m_buffer
Referenced by ~CBuffer, data, getSizeInBytes.
con::CBuffer::CBuffer(RawLayout &&lay) cond_noex
con::CBuffer::CBuffer(const CookedLayout &lay) cond_noex
con::CBuffer::CBuffer(CookedLayout &&lay) cond_noex
con::CBuffer::CBuffer(const CBuffer &rhs) noexcept
CBuffer & con::CBuffer::operator==(const CBuffer &rhs) noexcept
con::CBuffer::CBuffer(CBuffer &&rhs) noexcept
have to be careful with this one...
=================================================== the buffer that has once been pilfered must not be used
CBuffer & con::CBuffer::operator=(CBuffer &&rhs) noexcept
con::CBuffer::~CBuffer() noexcept
CBElementView con::CBuffer::operator[](const std::string &key) cond_noex
operator[] is how you begin indexing into buffer (root is always Struct)
if Buffer is const, you only get to index into the buffer with a read-only proxy
CBElementConstView con::CBuffer::operator[](const std::string &key) const cond_noex
const char * con::CBuffer::data() const noexcept
Referenced by IConstantBufferEx::IConstantBufferEx, IConstantBufferEx::update.
size_t con::CBuffer::getSizeInBytes() const noexcept
size of the raw byte buffer
Referenced by IConstantBufferEx::update.
const CBElement & con::CBuffer::getRootElement() const noexcept
Referenced by ConstantBufferEx< T >::getCbRootElement, IConstantBufferEx::update.
void con::CBuffer::copyFrom(const CBuffer &) cond_noex
copy bytes from another buffer (layouts must match)
Referenced by TransformScaleVSCB::operator=, ConstantBufferEx< T >::setBuffer.
void con::CBuffer::moveFrom(CBuffer &) noexcept
move bytes from another buffer (layouts must match)
std::shared_ptr< CBElement > con::CBuffer::shareLayoutRoot() const noexcept
return another sptr to the layout root