SettingsManager
struct SettingsManager::Settings SettingsManager::m_settings
Referenced by getSettings, getSettings, loadFromFile.
SettingsManager::SettingsManager(const std::string &filePath)
void SettingsManager::loadFromFile(const std::string &filePath)
Referenced by SettingsManager.
SettingsManager & SettingsManager::getInstance(const std::string &filePath="config.ini")
Referenced by Graphics::Graphics, ren::SkyPass::SkyPass, ren::ShadowPass::bindShadowCastingLights, Graphics::drawIndexed, Graphics::drawIndexedInstanced, firstly, Mesh::isFrustumCulled, Graphics::present, gui::UIPass::recreate, Window::windowProc_impl3d, wWinMain.
SettingsManager::Settings & SettingsManager::getSettings()
Referenced by Graphics::Graphics, Sandbox3d::Sandbox3d, ren::SkyPass::SkyPass, ren::ShadowPass::bindShadowCastingLights, Arkanoid::calcDt, Graphics::drawIndexed, Graphics::drawIndexedInstanced, Sandbox3d::loop, Graphics::present, Sandbox3d::render, Sandbox3d::update.
const SettingsManager::Settings & SettingsManager::getSettings() const