gui::Component
Dock_Point
Text_Justification
Aspect_Ratio_Locked_Behavior
using gui::Component::User_Property = std::pair<std::string, std::string>
unsigned gui::Component::s_texture_slot
Referenced by gui::Component::Component_State::Component_State.
Component* gui::Component::s_root
set when the first Component is created, see remarks @ Component ctor
Referenced by Component, ~Component, can_handle_hover, can_handle_press, create_component, evaluate_current_hover, get_root, is_attached_to_root, is_visible, update.
std::vector<Component*> gui::Component::s_top_most_components
refers to components in the ui hierarchy that are top most
Referenced by ~Component, is_top_most_or_child_of_top_most, render_top_most_components, set_enable_top_most.
std::vector<Component*> gui::Component::s_world_space_components
world space components collision shape is always relevant to a Mesh; but they are still rendered in screen space and as such always facing the camera, eg. "character health bar" is considered world space component
Referenced by ~Component, register_as_world_space, render_world_space_components.
float gui::Component::s_scale
float gui::Component::s_last_dt
Referenced by evaluate_current_hover, force_hover, update.
Component* gui::Component::s_last_hover
the component, excluding root, that was last hovered - updated on on_hover_off()
Referenced by ~Component, can_handle_hover, on_hover_off.
Component* gui::Component::s_current_hover
the component, excluding root, that is currently being hovered - updated on evaluate_current_hover()
Referenced by ~Component, can_handle_hover, divorce_child, evaluate_current_hover, force_hover, on_hover_off.
Point gui::Component::s_last_input_pos
Referenced by evaluate_current_hover, is_current_hover_over_any_child, render_tooltip, update.
float gui::Component::s_lerpBetweenFrames
set on update() by root
Referenced by update.
int gui::Component::s_current_tick
set on update() by root
Referenced by evaluate_current_hover, update, updated_last_tick.
int gui::Component::s_num_components
set on update() by root
Referenced by get_next_id, get_num_components, get_num_components_including_tooltips.
int gui::Component::s_num_tooltips
Referenced by Component, get_num_components_including_tooltips.
int gui::Component::m_id
Referenced by Component, get_id.
std::string gui::Component::m_name
Referenced by find_backward, find_forward, get_name, get_parent, switch_to_state.
int gui::Component::m_last_update_tick
Referenced by evaluate_current_hover, has_even_been_updated, on_hover_off, updated_last_tick.
float gui::Component::m_depth
Components with smaller depth numbers will render on top.
Referenced by Component, set_depth.
bool gui::Component::m_is_visible
root component is an imaginary component and is always invisible
Referenced by Component, can_handle_hover, can_handle_press, is_visible, render_regular_components, set_visibility.
bool gui::Component::m_update_when_not_visible
Referenced by can_handle_hover, can_handle_press.
bool gui::Component::m_is_topmost_object
Referenced by is_top_most, is_top_most_or_child_of_top_most, set_enable_top_most.
bool gui::Component::m_can_move
Referenced by Component.
bool gui::Component::m_is_tooltip
a tooltip Component will be created as a child of this one
Referenced by is_tooltip.
Aspect_Ratio_Locked_Behavior gui::Component::m_aspect_ratio_locked_behavior
Mesh* gui::Component::m_mesh
Referenced by is_world_space, register_as_world_space.
Component* gui::Component::m_parent
the parent Component of the root is nullptr
Referenced by Component, divorce_child, get_parent, get_parent, is_attached_to_root, is_visible_from_root, render_regular_components.
std::unique_ptr<Component> gui::Component::m_tooltip
tooltips do not exist in the main tree hierarchy, but are owned and managed by the individual components they exist in
Referenced by create_tooltip, render_tooltip.
std::vector<std::unique_ptr<Component> > gui::Component::m_children
this component's children, all events are passed down the hierarchy to children
Referenced by ~Component, create_component, divorce_child, evaluate_current_hover, get_child, get_child, get_children, get_children, get_children_count, is_current_hover_over_any_child, on_lmb_down, on_rmb_down, propagate_call, render_regular_components, resize.
std::vector<User_Property> gui::Component::m_user_properties
Referenced by ~Component, get_user_property_value, remove_user_property, set_user_property.
std::vector<std::unique_ptr<Component_State> > gui::Component::m_states
Referenced by Component, ~Component, resize, switch_to_state.
int gui::Component::m_current_state_index
Referenced by Component, switch_to_state.
bool gui::Component::create_component(Graphics &gfx, const std::string &name, const std::variant< Component *, std::string > parent, const int x, const int y, const int width, const int height, const bool is_tooltip=false, const std::vector< std::pair< std::string, std::string > > &state_texts={}, const std::vector< std::pair< std::string, std::string > > &state_image_paths={}, const DirectX::XMVECTORF32 &text_color=DirectX::Colors::White, const DirectX::XMFLOAT2 &text_scale=DirectX::XMFLOAT2{1.0f, 1.0f}, const std::string &tooltip_text="", Mesh *mesh=nullptr, const bool is_interactive=true, const bool is_enabled=false, const bool visible=true, const bool update_when_not_visible=false, const Aspect_Ratio_Locked_Behavior aspect_ratio_locked_behavior=Aspect_Ratio_Locked_Behavior::Aspect_Ratio_None, const Dock_Point docking=Dock_Point::Dock_Point_None, const Text_Justification text_justification=Text_Justification::Text_Justification_Left)
use this function to create a Component as a child of an existing parent Component
the root Component must already be constructed using the class ctor this function must have all the arguments and in the same order as the class ctor width & height will be automatically generarated for image components
Referenced by gui::UIPass::recreate.
Component * gui::Component::find_forward(Component *comp, const std::string &name, const bool is_recursive)
Referenced by create_component, find, find_forward.
Component * gui::Component::find_backward(const Component *comp, const std::string &name)
Referenced by find_backward.
int gui::Component::get_num_components()
int gui::Component::get_num_components_including_tooltips()
Component * gui::Component::get_root()
void gui::Component::update_world_space_components()
Referenced by update.
void gui::Component::render_world_space_components(Graphics &gfx, DirectX::SpriteBatch *pSpriteBatch, DirectX::SpriteFont *pSpriteFont, RasterizerState *pRasterizerState)
render ui components positioned in relevance to a mesh in 3d space
Referenced by render.
void gui::Component::render_top_most_components(Graphics &gfx, DirectX::SpriteBatch *pSpriteBatch, DirectX::SpriteFont *pSpriteFont, RasterizerState *pRasterizerState)
draws top most objects after rest of ui has been drawn (2d components, tooltips, WS components etc.)
Referenced by render.
gui::Component::Component(Graphics &gfx, const std::string &name, const std::variant< Component *, std::string > parent, const int x, const int y, const int width, const int height, const bool is_tooltip=false, const std::vector< std::pair< std::string, std::string > > &state_texts={}, const std::vector< std::pair< std::string, std::string > > &state_image_paths={}, const DirectX::XMVECTORF32 &text_color=DirectX::Colors::White, const DirectX::XMFLOAT2 &text_scale=DirectX::XMFLOAT2{1.0f, 1.0f}, const std::string &tooltip_text="", Mesh *mesh=nullptr, const bool is_interactive=true, const bool is_enabled=false, const bool visible=true, const bool update_when_not_visible=false, const Aspect_Ratio_Locked_Behavior aspect_ratio_locked_behavior=Aspect_Ratio_Locked_Behavior::Aspect_Ratio_None, const Dock_Point docking=Dock_Point::Dock_Point_None, const Text_Justification text_justification=Text_Justification::Text_Justification_Left)
you must supply either a non "" text, or an <component_state_str, image_path_str> argument
aside from the root all new Components should be created using the static function create_component by specifying the parent Component of the to-be-created-Component
gui::Component::~Component() noexcept
void gui::Component::create_tooltip(Graphics &gfx, const std::string &name, const int x, const int y, const int width, const int height, const std::vector< std::pair< std::string, std::string > > &state_texts, const DirectX::XMVECTORF32 &text_color=DirectX::Colors::White, const DirectX::XMFLOAT2 &text_scale=DirectX::XMFLOAT2{1.0f, 1.0f}, const Aspect_Ratio_Locked_Behavior aspect_ratio_locked_behavior=Aspect_Ratio_Locked_Behavior::Aspect_Ratio_None, const Dock_Point docking=Dock_Point::Dock_Point_None, const Text_Justification text_justification=Text_Justification::Text_Justification_Left)
Referenced by Component.
void gui::Component::notify(const SwapChainResizedEvent &event) override
void gui::Component::notify(const UserPropertyChanged &event) override
void gui::Component::notify(const UiMsg &event) override
void gui::Component::update(const float dt, const Point &input_pos, const float lerpBetweenFrames)
called for the root component once per tick; recursively called for entire ui hierarchy of root's children
void gui::Component::render(Graphics &gfx, DirectX::SpriteBatch *pSpriteBatch, DirectX::SpriteFont *pSpriteFont, RasterizerState *pRasterizerState)
bool gui::Component::updated_last_tick() const noexcept
Referenced by evaluate_current_hover.
void gui::Component::evaluate_current_hover()
called on update and when a component is removed form the hierachy
Referenced by divorce_child, update.
void gui::Component::force_hover(Component *comp, const bool should_handle_hover=true)
bool gui::Component::has_current_hover(const Point &input_pos) const noexcept
// the root Component always counts as hovered
Referenced by evaluate_current_hover, is_current_hover_over_any_child, render_tooltip.
bool gui::Component::is_current_hover_over_any_child() const noexcept
bool gui::Component::is_attached_to_root() const noexcept
Referenced by Component, is_attached_to_root.
void gui::Component::resize(const int width, const int height, const bool resize_children=true)
Referenced by notify, resize.
Component * gui::Component::find(const std::string &name)
retrieve the first found child component with given name
Referenced by Component, create_component.
void gui::Component::set_enable_top_most(const bool should_enable)
Referenced by ~Component.
bool gui::Component::is_top_most() const noexcept
bool gui::Component::is_top_most_or_child_of_top_most() const noexcept
int gui::Component::divorce_child(Component &component, const bool reevaluate_current_hover=true)
removes the specified child from our child list
returns the index of where the child was in the child list
void gui::Component::set_user_property(const std::string &prop, const std::string &value)
void gui::Component::remove_user_property(const std::string &property_name)
bool gui::Component::does_property_exist(const std::string &property_name) const noexcept
const std::string & gui::Component::get_user_property_value(T property_name) const
template to cover const char* and other string types
void gui::Component::move_to(const Point &p)
void gui::Component::move_relative(const Point &p)
Referenced by create_tooltip.
bool gui::Component::switch_to_state(const std::string &state_name)
void gui::Component::set_visibility(const bool is_visible)
Referenced by set_user_property.
void gui::Component::set_depth(const float depth)
void gui::Component::set_can_resize_width(const bool b)
Referenced by set_user_property.
void gui::Component::set_can_resize_height(const bool b)
Referenced by set_user_property.
void gui::Component::set_interactivity(const bool b)
void gui::Component::register_as_world_space(Mesh &mesh)
Referenced by Component.
bool gui::Component::is_parent_of(const Component &comp) const noexcept
checks whether supplied component is a parent, or ancenstor of this
const Component * gui::Component::get_parent() const noexcept
Referenced by find_backward, get_parent.
Component * gui::Component::get_parent()
const Component * gui::Component::get_parent(const std::string &name) const noexcept
retrieve a named parent component
Component * gui::Component::get_parent(const std::string &name)
const Component * gui::Component::get_child(const std::string &name) const noexcept
retrieve child with specified name
Referenced by find_forward.
Component * gui::Component::get_child(const std::string &name)
const Component * gui::Component::get_child(const unsigned index) const noexcept
retrieve child at specified index
Component * gui::Component::get_child(const unsigned index)
const std::vector< std::unique_ptr< Component > > & gui::Component::get_children() const noexcept
std::vector< std::unique_ptr< Component > > & gui::Component::get_children()
unsigned gui::Component::get_children_count() const noexcept
Referenced by find_forward.
bool gui::Component::can_resize_width() const noexcept
Referenced by resize.
bool gui::Component::can_resize_height() const noexcept
Referenced by resize.
bool gui::Component::has_text() const noexcept
bool gui::Component::has_image() const noexcept
bool gui::Component::is_tooltip() const noexcept
Referenced by create_component.
bool gui::Component::is_world_space() const noexcept
bool gui::Component::is_point_inside(const Point &point) const noexcept
Referenced by on_lmb_down, on_rmb_down.
int gui::Component::get_id() const noexcept
const std::string & gui::Component::get_name() const noexcept
bool gui::Component::is_visible() const noexcept
Referenced by is_visible_from_root, set_visibility.
bool gui::Component::is_visible_from_root() const noexcept
const Component::Component_State & gui::Component::get_current_state() const noexcept
Component::Component_State gui::Component::get_current_state()
Point gui::Component::get_position() const noexcept
int gui::Component::get_x() const noexcept
Referenced by get_position.
int gui::Component::get_y() const noexcept
Referenced by get_position.
int gui::Component::get_width() const noexcept
retrieve the width of the current state
Referenced by get_dimensions, resize.
int gui::Component::get_height() const noexcept
retrieve the height of the current state
Referenced by get_dimensions, resize.
Point gui::Component::get_dimensions() const noexcept
Component::Dock_Point gui::Component::get_docking() const noexcept
Component::Text_Justification gui::Component::get_text_justification() const noexcept
bool gui::Component::is_interactive() const noexcept
Referenced by Component, can_handle_hover, create_component.
bool gui::Component::is_enabled() const noexcept
Referenced by Component, can_handle_press, create_component.
bool gui::Component::has_even_been_updated() const noexcept
RectangleI gui::Component::get_collision_shape() const noexcept
Referenced by force_hover.
void gui::Component::on_lmb_down(const float dt, const Point &input_pos)
void gui::Component::on_rmb_down(const float dt, const Point &input_pos)
void gui::Component::propagate_call(const Callable &f)
Callable has this signature: void(*)(Component*)
void gui::Component::render_regular_components(Graphics &gfx, DirectX::SpriteBatch *pSpriteBatch, DirectX::SpriteFont *pSpriteFont, RasterizerState *pRasterizerState)
Referenced by render.
void gui::Component::render_tooltip(Graphics &gfx, DirectX::SpriteBatch *pSpriteBatch, DirectX::SpriteFont *pSpriteFont, RasterizerState *pRasterizerState)
Referenced by render_regular_components.
int gui::Component::get_next_id() const noexcept
bool gui::Component::validate_name(const std::string &name)
bool gui::Component::can_handle_hover() const noexcept
bool gui::Component::can_handle_press() const noexcept
Referenced by on_lmb_down, on_rmb_down.
void gui::Component::on_hover(const float dt, const Point &input_pos)
Referenced by evaluate_current_hover, force_hover.
void gui::Component::on_hover_off()
Referenced by evaluate_current_hover.