GraphicsFriend
ID3D11DeviceContext * GraphicsFriend::getDeviceContext(Graphics &gfx) noexcept
Referenced by Texture::Texture, PixelShaderConstantBuffer< CB >::bind, VertexShaderConstantBuffer< CB >::bind, IDepthStencilView::convertToBitmap, IRenderTargetView::convertToBitmap, IDepthStencilView::createStagingTexture, IRenderTargetView::createStagingTexture, PixelShaderConstantBuffer< CB >::makeCopy, VertexShaderConstantBuffer< CB >::makeCopy, Texture::paintTextureWithBitmap, gui::UIPass::recreate, IConstantBuffer< CB >::update, IConstantBufferEx::update.
ID3D11Device * GraphicsFriend::getDevice(Graphics &gfx) noexcept
Referenced by BlendState::BlendState, CubeTexture::CubeTexture, CubeTextureArrayOffscreenDS::CubeTextureArrayOffscreenDS, CubeTextureOffscreenDS::CubeTextureOffscreenDS, CubeTextureOffscreenRT::CubeTextureOffscreenRT, DepthStencilShaderInput::DepthStencilShaderInput, DepthStencilState::DepthStencilState, IConstantBuffer< CB >::IConstantBuffer, IConstantBuffer< CB >::IConstantBuffer, IConstantBufferEx::IConstantBufferEx, IDepthStencilView::IDepthStencilView, IDepthStencilView::IDepthStencilView, IDepthStencilView::IDepthStencilView, IndexBuffer::IndexBuffer, InputLayout::InputLayout, IRenderTargetView::IRenderTargetView, IRenderTargetView::IRenderTargetView, PixelShader::PixelShader, RasterizerState::RasterizerState, RenderTargetShaderInput::RenderTargetShaderInput, Texture::Texture, Texture::Texture, TextureArrayOffscreenDS::TextureArrayOffscreenDS, TextureOffscreenDS::TextureOffscreenDS, TextureOffscreenRT::TextureOffscreenRT, TextureSamplerState::TextureSamplerState, VertexBuffer::VertexBuffer, VertexShader::VertexShader, IDepthStencilView::createStagingTexture, IRenderTargetView::createStagingTexture, PixelShaderConstantBuffer< CB >::makeCopy, VertexShaderConstantBuffer< CB >::makeCopy, gui::UIPass::recreate.