ren::IPass
std::string ren::IPass::m_name
Referenced by getName.
bool ren::IPass::m_bActive
Referenced by isActive.
std::vector<std::unique_ptr<IBinder> > ren::IPass::m_binders
Referenced by addBinder, getBinder, getBinders, validate.
std::vector<std::unique_ptr<ILinker> > ren::IPass::m_linkers
Referenced by addLinker, getLinker, getLinkers.
ren::IPass::IPass(const std::string &name, bool bActive=true) noexcept
ren::IPass::~IPass() noexcept
virtual void ren::IPass::run(Graphics &gfx) const cond_noex=0
binds bindables & executes draw calls
virtual void ren::IPass::reset() cond_noex=0
const std::string & ren::IPass::getName() const noexcept
Referenced by getBinder, getLinker, ren::Renderer::linkPassBinders, ren::IBindablePass::validate.
const std::vector< std::unique_ptr< IBinder > > & ren::IPass::getBinders() const
Referenced by ren::Renderer::linkPassBinders.
const std::vector< std::unique_ptr< ILinker > > & ren::IPass::getLinkers() const
IBinder & ren::IPass::getBinder(const std::string &name) const
Referenced by setupBinderTarget.
ILinker & ren::IPass::getLinker(const std::string &name) const
void ren::IPass::setupBinderTarget(const std::string &binderName, const std::string &targetPassName, const std::string &targetPassLinkerName)
link a BindableBinder from this Pass to a Linker of another targetPass
void ren::IPass::validate()
validate binders are linked to their linkers
validation occurs only once (ctor) for every Pass
Referenced by ren::IBindablePass::validate.
void ren::IPass::setActive(const bool bActive) noexcept
const bool ren::IPass::isActive() const noexcept
void ren::IPass::recreateRtvsAndDsvs(Graphics &gfx)
void ren::IPass::addBinder(std::unique_ptr< IBinder > pBinder)
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, ren::DepthReversedPass::DepthReversedPass, ren::HorizontalBlurPass::HorizontalBlurPass, ren::OpaquePass::OpaquePass, ren::Pass2D::Pass2D, ren::RenderSurfaceClearPass::RenderSurfaceClearPass, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, ren::VerticalBlurPass::VerticalBlurPass, ren::WireframePass::WireframePass, ren::IBindablePass::addBindableBinderUsingContainerIndex.
void ren::IPass::addLinker(std::unique_ptr< ILinker > pLinker)
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, ren::DepthReversedPass::DepthReversedPass, ren::HorizontalBlurPass::HorizontalBlurPass, ren::OpaquePass::OpaquePass, ren::Pass2D::Pass2D, ren::RenderSurfaceClearPass::RenderSurfaceClearPass, ren::ShadowPass::ShadowPass, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, ren::VerticalBlurPass::VerticalBlurPass, ren::WireframePass::WireframePass.