DepthStencilState
Mode
Mode DepthStencilState::m_mode
Referenced by getUid.
Microsoft::WRL::ComPtr<ID3D11DepthStencilState> DepthStencilState::m_pDepthStencilState
Referenced by DepthStencilState, getD3dDepthStencilState.
DepthStencilState::DepthStencilState(Graphics &gfx, const Mode mode)
Referenced by calcUid.
void DepthStencilState::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
Microsoft::WRL::ComPtr< ID3D11DepthStencilState > & DepthStencilState::getD3dDepthStencilState()
std::string DepthStencilState::getUid() const noexcept override
std::shared_ptr< DepthStencilState > DepthStencilState::fetch(Graphics &gfx, const Mode mode)
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, ren::DepthReversedPass::DepthReversedPass, ren::OpaquePass::OpaquePass, ren::ShadowPass::ShadowPass, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, ren::WireframePass::WireframePass.
std::string DepthStencilState::calcUid(const Mode mode)
Referenced by getUid.