ren::IBinder
std::string ren::IBinder::m_name
Referenced by getName, setPassAndLinkerNames.
std::string ren::IBinder::m_passName
Referenced by getPassName, setPassAndLinkerNames.
std::string ren::IBinder::m_linkerName
Referenced by getLinkerName, setPassAndLinkerNames.
ren::IBinder::IBinder(const std::string &name)
virtual ren::IBinder::~IBinder()=default
void ren::IBinder::setPassAndLinkerNames(const std::string &passName, const std::string &linkerName)
virtual void ren::IBinder::link(ILinker &linker)=0
virtual void ren::IBinder::validateLinkage() const =0
assert validate after link()ing
const std::string & ren::IBinder::getName() const noexcept
Referenced by ren::BindableBinder< T >::link, ren::BindableBinder< T >::validateLinkage.
const std::string & ren::IBinder::getPassName() const noexcept
Referenced by ren::BindableBinder< T >::link.
const std::string & ren::IBinder::getLinkerName() const noexcept
Referenced by ren::BindableBinder< T >::link.