Bitmap
using Bitmap::Texel = ColorBGRA
DXGI_FORMAT Bitmap::s_format
Referenced by Bitmap, loadFromFile.
DirectX::ScratchImage Bitmap::m_scratchImg
Referenced by Bitmap, data, getHeight, getPitch, getSize, getWidth, hasAlpha, save.
Bitmap::Bitmap(DirectX::ScratchImage rhs) noexcept
Bitmap Bitmap::loadFromFile(const std::string &filename, unsigned wicFlags=DirectX::WIC_FLAGS_IGNORE_SRGB)
Referenced by CubeTexture::CubeTexture, Texture::Texture, gui::UIPass::recreate, TextureProcessor::transformFile, TextureProcessor::validateNormalMap.
const dx::XMVECTOR Bitmap::colorToVector(const Bitmap::Texel col) noexcept
convert from Color(0..255) to vector(-1..1)
Referenced by Terrain::Terrain, TextureProcessor::transformBitmap.
Bitmap::Texel Bitmap::vectorToColor(DirectX::XMVECTOR v) noexcept
Referenced by TextureProcessor::transformBitmap, TextureProcessor::transformBitmap.
Bitmap::Bitmap(const unsigned int width, const unsigned int height)
size_t Bitmap::getSize() const noexcept
void Bitmap::clear(const Texel fillValue) noexcept
void Bitmap::setTexel(const unsigned int x, const unsigned int y, const Texel col) cond_noex
Referenced by TextureProcessor::makeStripes, TextureProcessor::transformBitmap, TextureProcessor::transformBitmap.
const Bitmap::Texel Bitmap::getTexel(const unsigned int x, const unsigned int y) const cond_noex
Referenced by TextureProcessor::transformBitmap, TextureProcessor::transformBitmap.
unsigned int Bitmap::getWidth() const noexcept
Referenced by TextureProcessor::transformBitmap, TextureProcessor::transformBitmap.
unsigned int Bitmap::getHeight() const noexcept
Referenced by TextureProcessor::transformBitmap, TextureProcessor::transformBitmap.
unsigned int Bitmap::getPitch() const noexcept
=== getWidth() * sizeof Texel
Referenced by Texture::paintTextureWithBitmap.
Bitmap::Texel * Bitmap::data() noexcept
Referenced by getData.
const Bitmap::Texel * Bitmap::getData() const noexcept
Referenced by Texture::paintTextureWithBitmap.
void Bitmap::save(const std::string &filename, const unsigned wicFlags=DirectX::WIC_FLAGS_NONE) const
Referenced by TextureProcessor::makeStripes.
bool Bitmap::hasAlpha() const noexcept