VertexShader
std::string VertexShader::m_path
Referenced by getUid.
Microsoft::WRL::ComPtr<ID3DBlob> VertexShader::m_pVsBlob
Referenced by VertexShader, getBytecode.
Microsoft::WRL::ComPtr<ID3D11VertexShader> VertexShader::m_pVertexShader
Referenced by VertexShader.
VertexShader::VertexShader(Graphics &gfx, const std::string &filepath)
Referenced by calcUid.
void VertexShader::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
ID3DBlob * VertexShader::getBytecode() const noexcept
Referenced by InputLayout::InputLayout.
std::string VertexShader::getUid() const noexcept override
Referenced by InputLayout::calcUid.
std::shared_ptr< VertexShader > VertexShader::fetch(Graphics &gfx, const std::string &filepath)
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, CameraFrustum::CameraFrustum, CameraWidget::CameraWidget, Cube::Cube, Line::Line, ren::Pass2D::Pass2D, Plane::Plane, ren::ShadowPass::ShadowPass, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, Sphere::Sphere, Terrain::Terrain, testDynamicVertex.
std::string VertexShader::calcUid(const std::string &filepath)
Referenced by getUid.