ReportingNexus
ReporterAccess ReportingNexus::s_accessKey
Referenced by getInstance, getReporterAccess.
ReportingNexus::ReportingNexus(ReporterAccess &access)
ReportingNexus::~ReportingNexus() noexcept
ReportingNexus & ReportingNexus::getInstance()
Referenced by gui::Component::Component, Sandbox3d::Sandbox3d, SoundPlayer::SoundPlayer, gui::Component::on_hover, gui::Component::on_hover_off, gui::Component::remove_user_property, Graphics::resize, gui::Component::set_user_property.
ReporterAccess & ReportingNexus::getReporterAccess()