KeyException
int KeyException::m_line
Referenced by getLine, what.
std::string KeyException::m_file
Referenced by getFile, what.
std::string KeyException::m_function
Referenced by getFunction, what.
std::string KeyException::m_description
Referenced by what.
KeyException::KeyException(const int line, const char *file, const char *function, const std::string &msg) noexcept
virtual KeyException::~KeyException() noexcept=default
const char * KeyException::what() const noexcept override
Referenced by BindableException::what, Bitmap::BitmapException::what, Game< T >::GameException::what, GameplayException::what, Graphics::GraphicsException::what, ren::RendererException::what, UtilException::what, Window::WindowException::what, wWinMain.
std::string KeyException::getType() const noexcept
===================================================
Referenced by what, wWinMain.
unsigned KeyException::getLine() const noexcept
const std::string & KeyException::getFile() const noexcept
const std::string & KeyException::getFunction() const noexcept