Camera
float Camera::m_translationSpeed
float Camera::m_rotationSpeed
Referenced by getRotationSpeed.
float Camera::m_nearZ
Referenced by getPerspectiveProjectionMatrix, updateCameraFrustum.
float Camera::m_farZ
Referenced by getPerspectiveProjectionMatrix, updateCameraFrustum.
float Camera::m_NearZDefault
float Camera::m_FarZDefault
float Camera::m_width
Referenced by makeActive, updateCameraFrustum.
float Camera::m_height
Referenced by makeActive, updateCameraFrustum.
float Camera::m_widthDefault
float Camera::m_heightDefault
float Camera::m_aspectRatio
Referenced by getPerspectiveProjectionMatrix, updateCameraFrustum.
float Camera::m_fovRadians
Referenced by getFovRadians, getPerspectiveProjectionMatrix.
DirectX::XMFLOAT3 Camera::m_pos
Referenced by getPosition, getPosition, getPositionMatrix, getTarget, getViewMatrix.
DirectX::XMFLOAT3 Camera::m_posPrev
DirectX::XMFLOAT3 Camera::m_posDefault
float Camera::m_pitch
Referenced by getRotation, getRotationMatrix.
float Camera::m_pitchPrev
float Camera::m_pitchDefault
float Camera::m_yawDefault
float Camera::m_yaw
Referenced by getRotation, getRotationMatrix.
float Camera::m_yawPrev
bool Camera::m_bTethered
bool Camera::m_bPespectiveProjection
Referenced by makeActive.
bool Camera::m_bShowWidget
bool Camera::m_bShowFrustum
Model Camera::m_cameraWidget
Referenced by connectMaterialsToRenderer.
Model Camera::m_cameraFrustum
Referenced by connectMaterialsToRenderer, updateCameraFrustum.
std::string Camera::m_name
Referenced by getName.
DirectX::XMMATRIX Camera::getShadowOrthographicMatrix(const unsigned w, const unsigned h, const float shadowCamFarZ, const float shadowCamNearZ=1.0f) noexcept
DirectX::XMMATRIX Camera::getShadowProjectionMatrix(const float shadowCamFarZ, const float shadowCamNearZ=1.0f) noexcept
DirectX::XMVECTOR Camera::computeTargetVector(const DirectX::XMFLOAT3 &pos, const float pitchDeg, const float yawDeg) noexcept
std::pair< float, float > Camera::computePitchYawInDegFromDirectionVector(const DirectX::XMFLOAT3 &directionNormalized)
Referenced by DirectionalLight::DirectionalLight, SpotLight::SpotLight, computePitchYawRollInDegFromDirectionVector.
DirectX::XMFLOAT3 Camera::computePitchYawRollInDegFromDirectionVector(const DirectX::XMFLOAT3 &directionNormalized)
Camera::Camera(Graphics &gfx, const float width, const float height, const float fovDegrees=90.0f, const DirectX::XMFLOAT3 &posDefault={0.0f, 0.0f, 0.0f}, const float pitchDegDefault=0.0f, const float yawDegDefault=0.0f, const bool bTethered=false, const bool bPerspectiveProjection=true, const float nearZ=0.5f, const float farZ=200.0f, const DirectX::XMFLOAT4 camWidgetColor={0.2f, 0.2f, 0.6f, 1.0f}, const DirectX::XMFLOAT4 camFrustumColor={0.6f, 0.2f, 0.2f, 1.0f}, const float translationSpeed=16.0f, const float rotationSpeed=0.096f, const bool bShowDebugMeshes=false) noexcept
void Camera::update(const float dt, const float lerpBetweenFrames, const bool bEnableSmoothMovement=false) cond_noex
void Camera::render(const size_t channel=rch::all) const cond_noex
void Camera::connectMaterialsToRenderer(ren::Renderer &ren)
void Camera::makeActive(Graphics &gfx) const
Referenced by Sandbox3d::update.
void Camera::resetToDefault(Graphics &gfx) noexcept
DirectX::XMMATRIX Camera::getViewMatrix() const noexcept
Referenced by getFrustumPlanes, makeActive, DirectionalLight::populatePscbData, PointLight::populatePscbData.
DirectX::XMMATRIX Camera::getReflectionViewMatrix(const DirectX::XMVECTOR &mirrorPlane) const noexcept
DirectX::XMMATRIX Camera::getProjectionMatrix(Graphics &gfx, const bool bForShadows, const float shadowCamFarZ) const noexcept
Referenced by ren::ShadowPass::run.
DirectX::XMVECTOR Camera::getDirection() const noexcept
returns the vector describing the camera's direction - ie the direction the light is pointining - aka "lookVector"
Referenced by getRight, getTarget.
DirectX::XMVECTOR Camera::getRight() const noexcept
DirectX::XMVECTOR Camera::getUp() const noexcept
Referenced by getRight, getViewMatrix.
float Camera::getFovRadians() const noexcept
const std::string & Camera::getName() const noexcept
std::vector< dx::XMFLOAT4 > Camera::getFrustumPlanes() const noexcept
Referenced by Mesh::isFrustumCulled.
void Camera::displayImguiWidgets(Graphics &gfx) noexcept
void Camera::onWindowResize(Graphics &gfx)
void Camera::setTethered(const bool bTethered) cond_noex
void Camera::setRotationSpeed(const float rotationSpeed) noexcept
float Camera::getRotationSpeed() const noexcept
void Camera::setRotation(const DirectX::XMFLOAT3 &rot) noexcept
void Camera::rotateRel(const float dx, const float dy) noexcept
void Camera::translateRel(DirectX::XMFLOAT3 translation) noexcept
void Camera::setTranslation(const DirectX::XMFLOAT3 &pos) noexcept
const DirectX::XMFLOAT3 & Camera::getPosition() const noexcept
gets the camera matrix
Referenced by Mesh::getDistanceFromActiveCamera, ren::ShadowPass::run, Mesh::setDistanceFromActiveCamera.
DirectX::XMFLOAT3 & Camera::getPosition()
DirectX::XMFLOAT3 Camera::getRotation() const noexcept
DirectX::XMMATRIX Camera::getPositionMatrix() const noexcept
DirectX::XMMATRIX Camera::getRotationMatrix() const noexcept
Referenced by getDirection.
DirectX::XMVECTOR Camera::getTarget() const noexcept
target is the position of the camera's focus/focal point
ofc the camera doesn't look at a position, it looks along a direction; any points along that direction will do to compute the view-matrix
Referenced by getViewMatrix.
void Camera::updateCameraFrustum(Graphics &gfx)
DirectX::XMMATRIX Camera::getOrthographicProjectionMatrix(const unsigned width, const unsigned height) const noexcept
Referenced by makeActive.
DirectX::XMMATRIX Camera::getPerspectiveProjectionMatrix() const noexcept
Referenced by getFrustumPlanes, makeActive.