Window
Keyboard Window::s_keyboard
Referenced by getKeyboard, windowProc_impl2d, windowProc_impl3d.
Mouse Window::s_mouse
Referenced by getMouse, windowProc_impl2d, windowProc_impl3d.
std::vector<BYTE> Window::s_rawInputBuffer
Referenced by windowProc_impl2d, windowProc_impl3d.
HACCEL Window::s_hAcceleratorTable
Referenced by Window, messageLoop.
PLABELBOX Window::s_pBoxLocalClip
Referenced by editCopy, renderClipboardFormat, windowProc_impl3d.
UINT_PTR Window::s_timerEvent
Referenced by messageLoop, splashWindowTimerProc, windowProc_impl3d.
WindowClass Window::m_windowClass
Referenced by ~Window, getWindowClass.
bool Window::m_bCursorEnabled
Referenced by disableCursor, enableCursor, isCursorEnabled, windowProc_impl2d, windowProc_impl3d.
std::string Window::m_name
Referenced by Window::WindowClass::~WindowClass, getName, Window::WindowClass::getName.
std::string Window::m_title
Referenced by Window, getTitle.
HWND Window::m_hWnd
Referenced by Window, ~Window, confineCursor, displayMessageBoxOkCancel, displayMessageBoxYesNo, editCopy, editPaste, getDc, getHandle, getHeight, getHeightClientArea, getParent, getTopMenu, getWidth, getWidthClientArea, getWindowStyles, getWindowStylesEx, getX, getY, hideMenu, isActive, isHidden, isMaximized, isMinimized, messageLoop, minimize, processMenu, renderClipboardFormat, restore, setBorderless, setEnable, setFocus, setFont, setOnTop, setRedrawing, setTitle, setupSplashWindow, setupTrayIcon, setWindowStyles, setWindowStylesEx, showMenu, windowProc, windowProc_impl3d.
std::unique_ptr<Graphics> Window::m_pGraphics
Referenced by Window, getGraphics, windowProc_impl3d.
WINDOWINFO Window::m_info
Referenced by Window, getInfo.
std::array<unsigned, 8> Window::m_clipboardFormats
Referenced by Window, processMenu.
HMENU Window::m_hTrayIconPopupMenu
Referenced by windowProc_impl3d.
NOTIFYICONDATA Window::m_trayIconData
Referenced by deleteTrayIcon, setupTrayIcon, showTrayIcon.
std::unique_ptr<Window> Window::m_pModalDialog
Referenced by windowProc_impl3d.
std::unique_ptr<Window> Window::m_pSplash
Referenced by windowProc_impl3d.
LRESULT CALLBACK Window::windowProcDelegate(_In_ const HWND pWndHandle, _In_ const unsigned uMsg, _In_ const WPARAM wParam, _In_ const LPARAM lParam)
Referenced by windowProc.
int Window::messageBoxPrintf(const HWND window, const TCHAR *caption, const TCHAR *format,...)
a wrapper over Windows MessageBox function, first argument window can be nullptr
LRESULT CALLBACK Window::windowProc(_In_ const HWND pWnd, _In_ const unsigned uMsg, _In_ const WPARAM wParam, _In_ const LPARAM lParam)
LRESULT CALLBACK Window::dialogProc(_In_ const HWND hWnd, _In_ const unsigned uMsg, _In_ const WPARAM wParam, _In_ const LPARAM lParam)
Referenced by windowProc_impl3d.
LRESULT CALLBACK Window::splashWindowProc(_In_ const HWND hWnd, _In_ const unsigned uMsg, _In_ const WPARAM wParam, _In_ const LPARAM lParam)
Referenced by windowProc_impl3d.
void CALLBACK Window::splashWindowTimerProc(_In_ const HWND hWnd, _In_ const unsigned uMsg, _In_ const unsigned idEvent, _In_ const DWORD time)
Referenced by windowProc_impl3d.
Keyboard & Window::getKeyboard() noexcept
Referenced by Arkanoid::checkInput, Sandbox3d::checkInput.
Mouse & Window::getMouse() noexcept
Referenced by Sandbox3d::Sandbox3d, Arkanoid::checkInput, Sandbox3d::checkInput.
bool Window::isDescendantOf(const HWND targethWnd, const HWND parent) noexcept
void Window::saveClipboardTextAsVar()
HBITMAP Window::convertHiconToHbitmap(HICON hIcon)
hIcon vs hBitmap
hIcon is a handle to one of the system resources that Windows OS requires for providing a graphical USER interface. SHELL applications like Windows Explorer, Desktop etc, use this system resource extensively. hBITMAP is a graphical object which can be manipulated with GDI. hBitmaps can be altered with GDI either by selecting it to a DC or by manipulating the bits directly. GDI cannot handle an hICON.
HICON Window::convertHbitmapToHicon(HBITMAP bitmap)
Window::Window(const int width, const int height, const char *name, const char *className, const WNDPROC windowProcedure, const int x, const int y, const ColorBGRA bgColor={255, 255, 255}, const HMENU hMenu=nullptr, const Window *parent=nullptr)
Window::Window(Window &&rhs) noexcept
Window & Window::operator=(Window &&rhs) noexcept
Window::~Window()
std::optional< int > Window::messageLoop() noexcept
Referenced by Arkanoid::loop, Sandbox3d::loop.
void Window::setEnable(const bool b)
void Window::setOnTop()
const HWND Window::setFocus()
bool Window::hasParent() const noexcept
returns true if this Window has a parent that is not the Desktop window
Referenced by setupSplashWindow.
const HWND Window::getParent() const noexcept
Referenced by hasParent, setupSplashWindow.
void Window::setTitle(const std::string &title)
const std::string & Window::getTitle() const noexcept
Referenced by windowProc_impl3d.
void Window::enableCursor() noexcept
void Window::disableCursor() noexcept
bool Window::isCursorEnabled() const noexcept
Referenced by Arkanoid::checkInput, Sandbox3d::checkInput.
int Window::displayMessageBoxYesNo(const std::string &title, const std::string &message) const
Referenced by windowProc_impl3d.
int Window::displayMessageBoxOkCancel(const std::string &title, const std::string &message) const
bool Window::isActive() const noexcept
const std::string & Window::getName() const noexcept
void Window::minimize()
Referenced by windowProc_impl3d.
void Window::restore()
Referenced by windowProc_impl3d.
bool Window::isHidden() const noexcept
bool Window::isMinimized() const noexcept
bool Window::isMaximized() const noexcept
Window::operator bool() const noexcept
Graphics & Window::getGraphics()
Referenced by Sandbox3d::Sandbox3d, Sandbox3d::checkInput, Arkanoid::loop, Sandbox3d::loop, testDynamicVertex.
const HWND Window::getHandle() const noexcept
Referenced by Window.
HDC Window::getDc() const noexcept
get Window's Device Context (DC) - a "device context" contains information about the drawing attributes of a device such as a display or a printer, so if you have two different DC's, you're drawing in two different places; like a file handle for drawing
Referenced by ~Window.
WINDOWINFO Window::getInfo() const noexcept
unsigned Window::getWindowStyles() const noexcept
Referenced by setBorderless.
unsigned Window::getWindowStylesEx() const noexcept
Referenced by setBorderless.
void Window::setWindowStyles(const unsigned windowStyles) const noexcept
void Window::setWindowStylesEx(const unsigned windowStylesEx) const noexcept
void Window::setBorderless() const noexcept
void Window::setRedrawing(const bool bRedraw)
prevent intermediate redrawing
Referenced by hideMenu, showMenu.
void Window::showMenu(const HMENU hMenu)
Referenced by Window.
void Window::hideMenu()
Referenced by windowProc_impl3d.
const HMENU Window::getTopMenu() const noexcept
HWND Window::getDesktop() const noexcept
int Window::getX() const noexcept
int Window::getY() const noexcept
int Window::getWidth() const noexcept
Referenced by windowProc_impl2d, windowProc_impl3d.
int Window::getWidthClientArea() const noexcept
Referenced by windowProc_impl3d.
int Window::getHeight() const noexcept
Referenced by windowProc_impl2d, windowProc_impl3d.
int Window::getHeightClientArea() const noexcept
Referenced by windowProc_impl3d.
HWND Window::getConsoleHandle() const
const Window::WindowClass & Window::getWindowClass() noexcept
void Window::setupSplashWindow(HBITMAP hSplashBitmap)
create an Alpha enabled Splash window for the main application window
We'll use a layered window to do it (recommended method for Windows 2000+). The beauty of layered windows and the UpdateLayeredWindow function is that the splash window doesn't have to respond to WM_PAINT messages; Windows will paint it (and blend it correctly with the windows below it) by default. #WARNING: load the BMP with black color for the transparent places
void Window::confineCursor() noexcept
Referenced by disableCursor, windowProc_impl2d, windowProc_impl3d.
void Window::freeCursor() noexcept
Referenced by enableCursor, windowProc_impl2d, windowProc_impl3d.
void Window::showCursor() noexcept
Referenced by enableCursor, windowProc_impl2d, windowProc_impl3d.
void Window::hideCursor() noexcept
Referenced by disableCursor, windowProc_impl2d, windowProc_impl3d.
void Window::enableImGuiMouse() noexcept
Referenced by enableCursor.
void Window::disableImGuiMouse() noexcept
Referenced by disableCursor.
LRESULT Window::windowProc_impl3d(_In_ const HWND pWndHandle, _In_ const unsigned msg, _In_ const WPARAM wparam, _In_ const LPARAM lparam)
Referenced by windowProcDelegate.
LRESULT Window::windowProc_impl2d(_In_ const HWND pWndHandle, _In_ const unsigned msg, _In_ const WPARAM wparam, _In_ const LPARAM lparam)
Referenced by windowProcDelegate.
void Window::setFont(const std::string &fontName)
void Window::setWindowProperties(const int width, const int height, const unsigned flags=SWP_NOZORDER|SWP_NOMOVE|SWP_NOACTIVATE) cond_noex
void WINAPI Window::processMenu(HMENU hMenu)
Menu related functions.
Referenced by windowProc_impl3d.
bool Window::editCopy(const unsigned format=CLIPBOARD_TEXT_FORMAT)
Referenced by windowProc_impl3d.
bool Window::editPaste(const unsigned format=CLIPBOARD_TEXT_FORMAT)
Referenced by windowProc_impl3d.
void Window::renderClipboardFormat(unsigned format=CLIPBOARD_TEXT_FORMAT)
Referenced by windowProc_impl3d.
void Window::editDelete()
delete selected text, eg as if you pressed "cut" or the "delete" key
Referenced by windowProc_impl3d.
void Window::setupTrayIcon()
Referenced by Window.
void Window::showTrayIcon() noexcept
Referenced by windowProc_impl2d, windowProc_impl3d.
void Window::deleteTrayIcon() noexcept
Referenced by ~Window, windowProc_impl3d.