InputLayout
Microsoft::WRL::ComPtr<ID3D11InputLayout> InputLayout::m_pInputLayout
Referenced by InputLayout.
std::string InputLayout::m_vertexShaderUID
Referenced by getUid.
ver::VertexInputLayout InputLayout::m_vertexLayout
Referenced by InputLayout, getLayout, getUid.
InputLayout::InputLayout(Graphics &gfx, const ver::VertexInputLayout &layout, const VertexShader &vs)
Referenced by calcUid, getUid.
void InputLayout::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
const ver::VertexInputLayout InputLayout::getLayout() const noexcept
std::string InputLayout::getUid() const noexcept override
std::shared_ptr< InputLayout > InputLayout::fetch(Graphics &gfx, const ver::VertexInputLayout &layout, const VertexShader &vs)
Referenced by CameraFrustum::CameraFrustum, CameraWidget::CameraWidget, Cube::Cube, Line::Line, ren::Pass2D::Pass2D, Plane::Plane, ren::SkyPass::SkyPass, Sphere::Sphere, Terrain::Terrain, testDynamicVertex.
std::string InputLayout::calcUid(const ver::VertexInputLayout &layout, const VertexShader &vs)