Graphics
friend class GraphicsFriend
D3D_FEATURE_LEVEL Graphics::s_featureLevel
Referenced by Graphics, Graphics::Adapter::getVRamDetails.
std::vector<Adapter> Graphics::s_adapters
Referenced by Graphics, createAdapters, setupMonitors.
unsigned Graphics::m_width
Referenced by beginFrame, drawLine, getClientWidth, getDepthBufferOffscreen, getRenderTargetOffscreen, putPixel, resize.
unsigned Graphics::m_height
Referenced by beginFrame, drawLine, getClientHeight, getDepthBufferOffscreen, getRenderTargetOffscreen, putPixel, resize.
HWND Graphics::m_hParentWnd
Referenced by interrogateDirectxFeatures.
UINT Graphics::m_swapChainFlags
Referenced by Graphics, resize.
Microsoft::WRL::ComPtr<IDXGIFactory1> Graphics::m_pDxgiFactory
Referenced by Graphics, checkTearingSupport, createAdapters, createFactory, makeWindowAssociationWithFactory.
Microsoft::WRL::ComPtr<IDXGISwapChain> Graphics::m_pSwapChain
Referenced by Graphics, bindBackBufferAsInput, getRenderTargetFromBackBuffer, present, profile, resize, setupMonitors.
Microsoft::WRL::ComPtr<ID3D11Device> Graphics::m_pDevice
Referenced by Graphics, bindBackBufferAsInput, getRefreshRate, interrogateDirectxFeatures, present.
Microsoft::WRL::ComPtr<ID3D11DeviceContext> Graphics::m_pImmediateContext
Referenced by Graphics, bindBackBufferAsInput, cleanState, clearShaderSlots.
Microsoft::WRL::ComPtr<IDXGIOutput1> Graphics::m_pDxgiOutput
Referenced by getRefreshRate, resize, setupMonitors.
std::shared_ptr<RenderTargetOutput> Graphics::m_pBackBufferRtv
Referenced by getRenderTargetFromBackBuffer, resize.
std::shared_ptr<DepthStencilOutput> Graphics::m_pBackBufferDsv
Referenced by getDepthBufferFromBackBuffer, resize.
std::shared_ptr<TextureOffscreenRT> Graphics::m_pOffscreenRtv
Referenced by getRenderTargetOffscreen, resize.
std::shared_ptr<TextureOffscreenDS> Graphics::m_pOffscreenDsv
Referenced by getDepthBufferOffscreen, resize.
DirectX::XMMATRIX Graphics::m_projection
Referenced by getProjectionMatrix.
DirectX::XMMATRIX Graphics::m_view
Referenced by getViewMatrix.
size_t Graphics::m_currentFrame
Referenced by beginFrame, getFrameNum.
std::vector<ID3D11DeviceContext*> Graphics::m_deferredContexts
Referenced by Graphics.
std::vector<ID3D11CommandList*> Graphics::m_commandLists
Referenced by Graphics, cleanState.
std::unique_ptr<ren::Renderer> Graphics::m_pRenderer
Referenced by Graphics, endFrame, getRenderer, resize, runRenderer.
ren::Renderer3d* Graphics::m_pRenderer3d
Referenced by Graphics, getRenderer3d.
ren::Renderer2d* Graphics::m_pRenderer2d
Referenced by Graphics, getRenderer2d.
KeyTimer<std::chrono::microseconds> Graphics::m_fpsTimer
Referenced by Graphics, getFpsTimer.
KeyTimer<std::chrono::seconds> Graphics::m_realTimer
Referenced by Graphics, getRealTimer.
bool Graphics::m_bFullscreenMode
Referenced by getDisplayMode, getDisplayMode, resize.
ColorBGRA* Graphics::m_pCpuBuffer
d2d via d3d Interoperability
Referenced by Graphics, ~Graphics, beginFrame, cpuBuffer, putPixel.
Graphics::Graphics(const HWND hWnd, const int width, const int height, const MultisamplingMode multisamplingMode=MultisamplingMode::None)
Graphics::~Graphics()
void Graphics::makeWindowAssociationWithFactory(HWND hWnd, const UINT flags)
Referenced by Graphics.
void Graphics::profile() const noexcept
void Graphics::clearShaderSlots() noexcept
Referenced by beginFrame, cleanState.
void Graphics::cleanState() noexcept
Referenced by ~Graphics.
void Graphics::beginFrame() noexcept
Referenced by Arkanoid::render, Sandbox3d::render.
void Graphics::endFrame()
Referenced by Game< T >::present.
void Graphics::draw(const unsigned count) cond_noex
void Graphics::drawIndexed(const unsigned count) cond_noex
void Graphics::drawIndexedInstanced(const unsigned indexCount, const unsigned instanceCount) cond_noex
ColorBGRA *& Graphics::cpuBuffer()
void Graphics::setViewMatrix(const DirectX::XMMATRIX &cam) noexcept
Referenced by Camera::makeActive.
void Graphics::setProjectionMatrix(const DirectX::XMMATRIX &proj) noexcept
Referenced by Camera::makeActive.
const dx::XMMATRIX & Graphics::getViewMatrix() const noexcept
Referenced by MousePicker::convertToWorldSpace.
const dx::XMMATRIX & Graphics::getProjectionMatrix() const noexcept
Referenced by MousePicker::convertToClip, MousePicker::convertToViewSpace.
unsigned Graphics::getClientWidth() const noexcept
Referenced by ren::HorizontalBlurPass::HorizontalBlurPass, ren::Pass2D::Pass2D, PointLight::PointLight, MousePicker::convertToNdc, gui::Component::notify, gui::UIPass::recreate.
unsigned Graphics::getClientHeight() const noexcept
Referenced by ren::HorizontalBlurPass::HorizontalBlurPass, ren::Pass2D::Pass2D, PointLight::PointLight, MousePicker::convertToNdc, gui::Component::notify, gui::UIPass::recreate.
std::shared_ptr< RenderTargetOutput > Graphics::getRenderTargetFromBackBuffer()
Referenced by ren::Renderer::offscreenToBackBufferSwap, ren::Renderer::recreate, resize.
std::shared_ptr< DepthStencilOutput > Graphics::getDepthBufferFromBackBuffer()
Referenced by ren::Renderer::recreate, resize.
std::shared_ptr< TextureOffscreenRT > Graphics::getRenderTargetOffscreen(const unsigned slot, const RenderTargetViewMode rtvMode)
Referenced by ren::Renderer::offscreenToBackBufferSwap, ren::Renderer::recreate, resize.
std::shared_ptr< TextureOffscreenDS > Graphics::getDepthBufferOffscreen(const unsigned slot, const DepthStencilViewMode dsvMode)
Referenced by ren::Renderer::recreate, resize.
void Graphics::bindBackBufferAsInput()
void Graphics::createFactory()
Referenced by Graphics.
void Graphics::createAdapters()
Referenced by Graphics.
void Graphics::resize(unsigned newWidth, unsigned newHeight)
sets windowed mode or Fullscreen, supply width & height of 0 to resize the buffers for fullscreen mode usage
void Graphics::setupMonitors()
sets up the output monitor devices
Referenced by Graphics.
double Graphics::getRefreshRate() const noexcept
Referenced by Graphics.
size_t Graphics::getFrameNum() const noexcept
void Graphics::runRenderer() noexcept
Referenced by Arkanoid::render, Sandbox3d::render.
ren::Renderer & Graphics::getRenderer() noexcept
ren::Renderer3d & Graphics::getRenderer3d() noexcept
Referenced by Sandbox3d::checkInput, Sandbox3d::render, Sandbox3d::test, Sandbox3d::update.
ren::Renderer2d & Graphics::getRenderer2d() noexcept
KeyTimer< std::chrono::microseconds > & Graphics::getFpsTimer() noexcept
Referenced by gui::Component::Component_State::Component_State.
KeyTimer< std::chrono::seconds > & Graphics::getRealTimer() noexcept
bool Graphics::getDisplayMode() const noexcept
returns true if fullscreen application, false otherwise
bool & Graphics::getDisplayMode()
void Graphics::recordDeferredCommandList()
probably should call this when the Model is being loaded not when pass->run() -> Job->run()
void Graphics::playbackDeferredCommandList()
ExecuteCommandList must be executed on the immediate context for recorded commands to be run on the GPU.
ColorBGRA Graphics::getPixel(const int x, const int y) const noexcept
d2d via d3d Interoperability
void Graphics::putPixel(const int x, const int y, const ColorBGRA color)
Referenced by drawCircle, drawLine, drawRectangle, drawStar, putPixel.
void Graphics::putPixel(const int x, const int y, const int r, const int g, const int b)
void Graphics::drawLine(int x0, int x1, int y0, int y1, const ColorBGRA col)
uses the Bresenham algorithm to draw lines, ie. connect 2d positions together by drawing straight lines between them
Referenced by drawTriangle.
void Graphics::drawRectangle(int x0, int y0, int x1, int y1, const ColorBGRA col)
Referenced by drawRectangle, drawRectWH.
void Graphics::drawRectangle(const RectangleF &rect, const ColorBGRA col)
void Graphics::drawRectWH(const int x0, const int y0, const int width, const int height, const ColorBGRA col)
void Graphics::drawTriangle(int x0, int y0, int x1, int y1, int x2, int y2, const ColorBGRA col)
void Graphics::drawCircle(const int centerX, const int centerY, const int radius, const ColorBGRA col)
void Graphics::drawStar(const float outerRadius, const float innerRadius, const ColorBGRA color, const int nFlares=5)
void Graphics::present()
present the frame to DWM
Referenced by endFrame.
void Graphics::interrogateDirectxFeatures()
Referenced by Graphics.
bool Graphics::checkTearingSupport()
Referenced by Graphics.