PixelShader
std::string PixelShader::m_path
Referenced by getUid.
Microsoft::WRL::ComPtr<ID3DBlob> PixelShader::m_pPsBlob
Referenced by PixelShader, getBytecode.
Microsoft::WRL::ComPtr<ID3D11PixelShader> PixelShader::m_pPixelShader
Referenced by PixelShader.
PixelShader::PixelShader(Graphics &gfx, const std::string &filepath)
Referenced by calcUid.
void PixelShader::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
ID3DBlob * PixelShader::getBytecode() const noexcept
std::string PixelShader::getUid() const noexcept override
std::shared_ptr< PixelShader > PixelShader::fetch(Graphics &gfx, const std::string &filepath)
Referenced by ren::BlurPass::BlurPass, CameraFrustum::CameraFrustum, CameraWidget::CameraWidget, Cube::Cube, ren::HorizontalBlurPass::HorizontalBlurPass, Line::Line, ren::NegativePass::NegativePass, ren::PassThrough::PassThrough, Plane::Plane, ren::SkyPass::SkyPass, ren::SolidOutlineDrawPass::SolidOutlineDrawPass, Sphere::Sphere, Terrain::Terrain, ren::VerticalBlurPass::VerticalBlurPass, testDynamicVertex.
std::string PixelShader::calcUid(const std::string &filepath)
Referenced by getUid.