Model
int Model::m_nNodes
int Model::m_nMeshNodes
std::string Model::m_name
Referenced by Model, getName.
std::unique_ptr<Node> Model::m_pRoot
Referenced by Model, accept, getPosition, getRotation, getRotationQuat, getScale, getScale3, getTransform, getTransform4x4, scaleRel.
std::vector<std::unique_ptr<Mesh> > Model::m_meshes
Referenced by Model, ~Model, connectMaterialsToRenderer, getMesh.
ImguiPerModelNodeVisitor Model::m_imguiVisitor
Referenced by Model.
Model::Model(Graphics &gfx, const std::string &path, const float initialScale=1.0f, const DirectX::XMFLOAT3 &initialRotDeg={0.0f, 0.0f, 0.0f}, const DirectX::XMFLOAT3 &initialPos={0.0f, 0.0f, 0.0f})
Model ctor for imported meshes.
initialRot is in degrees - it will be converted and stored as radians
Model::Model(std::unique_ptr< Mesh > pMesh, Graphics &gfx, const DirectX::XMFLOAT3 &initialRotDeg, const DirectX::XMFLOAT3 &initialPos)
ctor for single-Mesh/Node primitives
initialRot is in degrees - it will be converted and stored as radians
Model::~Model() noexcept
Model::Model(const Model &rhs)=delete
Model & Model::operator=(const Model &rhs)=delete
Model::Model(Model &&rhs) noexcept
Model & Model::operator=(Model &&rhs) noexcept=delete
void Model::update(const float dt, const float lerpBetweenFrames, const bool bEnableSmoothMovemenzzt=false) cond_noex
void Model::render(const size_t channels=rch::all) const cond_noex
Referenced by Sandbox3d::render.
void Model::setMaterialEnabled(const size_t channels, const bool bEnabled) noexcept
Referenced by Sandbox3d::connectToRenderer.
void Model::displayImguiWidgets(Graphics &gfx) noexcept
Referenced by Sandbox3d::test.
void Model::accept(IImguiNodeVisitor &v)
void Model::connectMaterialsToRenderer(ren::Renderer &r)
Referenced by Camera::connectMaterialsToRenderer, ILightSource::connectMaterialsToRenderer, Sandbox3d::connectToRenderer.
void Model::setScale(const float scale) cond_noex
void Model::setScale(const DirectX::XMFLOAT3 &scale) cond_noex
void Model::scaleRel(const DirectX::XMFLOAT3 &scale) cond_noex
void Model::setRotation(const DirectX::XMFLOAT3 &rotAnglesRadians) cond_noex
Referenced by ILightSource::setRotation.
void Model::rotateRel(const DirectX::XMFLOAT3 &rotAnglesRadians) cond_noex
void Model::setTranslation(const DirectX::XMFLOAT3 &pos) cond_noex
Referenced by ILightSource::setTranslation.
void Model::translateRel(const DirectX::XMFLOAT3 &pos) cond_noex
DirectX::XMMATRIX Model::getTransform() const noexcept
DirectX::XMFLOAT4X4 Model::getTransform4x4() const noexcept
float Model::getScale() const noexcept
DirectX::XMFLOAT3 Model::getScale3() const noexcept
DirectX::XMFLOAT3 Model::getRotation() const noexcept
Referenced by ILightSource::getRotation.
DirectX::XMVECTOR Model::getRotationQuat() const noexcept
DirectX::XMFLOAT3 Model::getPosition() const noexcept
Referenced by DirectionalLight::getPosition.
float Model::getDistanceFromActiveCamera(const int index=0) const noexcept
return the distance between the currently active camera and the Mesh at specified index
if index == 0 -> it's the root Node's Mesh
const std::string & Model::getName() const noexcept
const Mesh *const Model::getMesh(const int index=0) const noexcept
Referenced by Camera::updateCameraFrustum.
Mesh *const Model::getMesh(const int index=0)
void Model::setTransform(const DirectX::XMMATRIX &tr) cond_noex
All transformation-related-functions simply call the root Node's corresponding function and propagate the operation down the Node hierarchy; the world transform itself is updated only once-per-tick during update.
Referenced by Model.
void Model::setTransform(const float scale, const DirectX::XMFLOAT3 &rotAnglesRadians, const DirectX::XMFLOAT3 &pos) cond_noex
void Model::setTransform(const float scale, const DirectX::XMFLOAT4 &rotQuat, const DirectX::XMFLOAT3 &pos) cond_noex
void Model::setTransform(const float scale, const DirectX::XMVECTOR &rotQuat, const DirectX::XMFLOAT3 &pos) cond_noex
std::unique_ptr< Node > Model::parseModelNodeGraph(Node *pParent, const aiNode &node, int imguiNodeId, const float initialScale) cond_noex