PrimitiveTopology
D3D11_PRIMITIVE_TOPOLOGY PrimitiveTopology::m_d3dTopology
Referenced by getUid.
PrimitiveTopology::PrimitiveTopology(Graphics &gfx, const D3D11_PRIMITIVE_TOPOLOGY topology)
Referenced by calcUid.
void PrimitiveTopology::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
std::string PrimitiveTopology::getUid() const noexcept override
std::shared_ptr< PrimitiveTopology > PrimitiveTopology::fetch(Graphics &gfx, const D3D11_PRIMITIVE_TOPOLOGY topology)
Referenced by CameraFrustum::CameraFrustum, CameraWidget::CameraWidget, Cube::Cube, Line::Line, Mesh::Mesh, ren::Pass2D::Pass2D, Plane::Plane, ren::SkyPass::SkyPass, Sphere::Sphere, Terrain::Terrain, testDynamicVertex.
std::string PrimitiveTopology::calcUid(const D3D11_PRIMITIVE_TOPOLOGY topology)
Referenced by getUid.