TextureProcessor
static void TextureProcessor::transformFile(const std::string &pathIn, const std::string &pathOut, F &&f)
Referenced by flipNormalMapGreenChannel.
const unsigned TextureProcessor::calculateNumberOfMipMaps(const unsigned width, const unsigned height) noexcept
void TextureProcessor::flipModelNormalMapsGreenChannel(const std::string &objPath)
void TextureProcessor::flipNormalMapGreenChannel(const std::string &pathIn, const std::string &pathOut)
flips the normal map green channel of given texture
Referenced by flipModelNormalMapsGreenChannel.
void TextureProcessor::validateNormalMap(const std::string &pathIn, const float thresholdMin, const float thresholdMax)
void TextureProcessor::makeStripes(const std::string &pathOut, const int size, const int stripeWidth)
void TextureProcessor::transformBitmap(Bitmap &bitmap, TextureOp f)
apply function f at every Texel in the Bitmap
Referenced by Texture::Texture, transformFile, validateNormalMap.
static void TextureProcessor::transformBitmap(Bitmap &bitmap, F &&f)