MousePicker
DirectX::XMFLOAT3 MousePicker::m_rayDirectionWorldSpace
Referenced by MousePicker.
MousePicker::MousePicker(Graphics &gfx, int screenX, int screenY)
DirectX::XMFLOAT2 MousePicker::convertToNdc(Graphics &gfx, const DirectX::XMFLOAT2 &coordsScreenSpace)
Referenced by MousePicker.
DirectX::XMFLOAT2 MousePicker::convertToClip(Graphics &gfx, const DirectX::XMFLOAT2 &coordsNdc)
Referenced by MousePicker.
DirectX::XMVECTOR MousePicker::convertToViewSpace(Graphics &gfx, const DirectX::XMFLOAT2 &coordsClip)
Referenced by MousePicker.
DirectX::XMVECTOR MousePicker::convertToWorldSpace(Graphics &gfx, const DirectX::XMFLOAT4 &coordsView)
Referenced by MousePicker.