IImGuiConstantBufferVisitor
Material* IImGuiConstantBufferVisitor::m_pMaterial
Referenced by ImguiConstantBufferVisitorShowcase::onSetMaterial, setMaterial.
size_t IImGuiConstantBufferVisitor::m_materialId
Referenced by ImguiConstantBufferVisitorShowcase::onSetMaterial, setMaterial.
size_t IImGuiConstantBufferVisitor::m_imguiId
Referenced by ImguiConstantBufferVisitorShowcase::onVisit, visit.
virtual IImGuiConstantBufferVisitor::~IImGuiConstantBufferVisitor() noexcept=default
void IImGuiConstantBufferVisitor::setMaterial(Material *ef)
Referenced by Material::accept.
bool IImGuiConstantBufferVisitor::visit(con::CBuffer &cb)
returns true if concrete bindable (with a con::CBuffer) requires an update
Referenced by ConstantBufferEx< T >::accept, TransformScaleVSCB::accept.
virtual bool IImGuiConstantBufferVisitor::onVisit(con::CBuffer &cb)=0
Referenced by visit.
virtual void IImGuiConstantBufferVisitor::onSetMaterial()=0
Referenced by setMaterial.