CameraManager
CameraManager* CameraManager::s_pInstance
int CameraManager::m_activeCameraIndex
Referenced by getActiveCamera, getActiveCamera, render, shareActiveCamera.
int CameraManager::m_controlledCameraIndex
Referenced by getControlledCamera, getControlledCamera, shareControlledCamera.
std::vector<std::shared_ptr<Camera> > CameraManager::m_cameras
Referenced by add, connectMaterialsToRenderer, getActiveCamera, getActiveCamera, getControlledCamera, getControlledCamera, onWindowResize, render, shareActiveCamera, shareControlledCamera.
CameraManager::CameraManager()=default
CameraManager & CameraManager::getInstance()
Referenced by MousePicker::MousePicker, Mesh::getDistanceFromActiveCamera, Mesh::isFrustumCulled, DirectionalLight::populatePscbData, PointLight::populatePscbData, Graphics::resize, Mesh::setDistanceFromActiveCamera.
void CameraManager::displayImguiWidgets(Graphics &gfx) noexcept
Referenced by Sandbox3d::test.
void CameraManager::add(std::shared_ptr< Camera > pCam)
Referenced by Sandbox3d::Sandbox3d.
void CameraManager::connectMaterialsToRenderer(ren::Renderer &r)
Referenced by Sandbox3d::connectToRenderer.
void CameraManager::render(const size_t channels=rch::all) const
Referenced by Sandbox3d::render.
void CameraManager::onWindowResize(Graphics &gfx)
Referenced by Graphics::resize.
Camera & CameraManager::getActiveCamera() cond_noex
Referenced by Sandbox3d::checkInput, Mesh::getDistanceFromActiveCamera, Mesh::isFrustumCulled, DirectionalLight::populatePscbData, PointLight::populatePscbData, Mesh::setDistanceFromActiveCamera, Sandbox3d::update.
const Camera & CameraManager::getActiveCamera() const noexcept
std::shared_ptr< Camera > CameraManager::shareActiveCamera() const noexcept
Camera & CameraManager::getControlledCamera() cond_noex
const Camera & CameraManager::getControlledCamera() const noexcept
std::shared_ptr< Camera > CameraManager::shareControlledCamera() const noexcept