RasterizerState
RasterizerMode
FillMode
FaceMode
Microsoft::WRL::ComPtr<ID3D11RasterizerState> RasterizerState::m_pRasterizerState
Referenced by RasterizerState, getD3dRasterizerState.
RasterizerMode RasterizerState::m_mode
Referenced by getMode, getUid.
FillMode RasterizerState::m_fillMode
Referenced by getUid.
FaceMode RasterizerState::m_faceMode
Referenced by getUid.
int RasterizerState::m_depthBias
Referenced by getUid.
float RasterizerState::m_slopeBias
Referenced by getUid.
float RasterizerState::m_biasClamp
Referenced by getUid.
RasterizerState::RasterizerState(Graphics &gfx, const RasterizerMode mode, const FillMode fillMode, const FaceMode faceMode, const int depthBias=D3D11_DEFAULT_DEPTH_BIAS, const float slopeBias=D3D11_DEFAULT_SLOPE_SCALED_DEPTH_BIAS, const float biasClamp=D3D11_DEFAULT_DEPTH_BIAS_CLAMP)
if mode is RasterizerMode::ShadowRS then fillMode and faceMode values will be defaulted
if mode is RasterizerMode::DefaultRS then depthBias, slopeBias and biasClamp will be defaulted
Referenced by calcUid.
void RasterizerState::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
std::string RasterizerState::getUid() const noexcept override
RasterizerState::RasterizerMode RasterizerState::getMode() const noexcept
Microsoft::WRL::ComPtr< ID3D11RasterizerState > & RasterizerState::getD3dRasterizerState()
Referenced by gui::Component::Component_State::draw_texture.
std::shared_ptr< RasterizerState > RasterizerState::fetch(Graphics &gfx, const RasterizerMode mode, const FillMode fillMode, const FaceMode faceMode, const int depthBias=D3D11_DEFAULT_DEPTH_BIAS, const float slopeBias=D3D11_DEFAULT_SLOPE_SCALED_DEPTH_BIAS, const float biasClamp=D3D11_DEFAULT_DEPTH_BIAS_CLAMP)
Referenced by ren::BlurOutlineMaskPass::BlurOutlineMaskPass, Cube::Cube, Line::Line, ren::Pass2D::Pass2D, Plane::Plane, ren::ShadowPass::ShadowPass, ren::SkyPass::SkyPass, ren::SolidOutlineMaskPass::SolidOutlineMaskPass, Sphere::Sphere, Terrain::Terrain, ren::WireframePass::WireframePass, gui::UIPass::recreate.
std::string RasterizerState::calcUid(const RasterizerMode mode, const FillMode fillMode, const FaceMode faceMode, const int depthBias=D3D11_DEFAULT_DEPTH_BIAS, const float slopeBias=D3D11_DEFAULT_SLOPE_SCALED_DEPTH_BIAS, const float biasClamp=D3D11_DEFAULT_DEPTH_BIAS_CLAMP)
Referenced by getUid.