TextureSamplerState
TextureSamplerMode
FilterMode
AddressMode
Microsoft::WRL::ComPtr<ID3D11SamplerState> TextureSamplerState::m_pSamplerState
Referenced by TextureSamplerState.
unsigned TextureSamplerState::m_slot
Referenced by getSlot.
TextureSamplerMode TextureSamplerState::m_mode
Referenced by getUid.
FilterMode TextureSamplerState::m_filteringMode
Referenced by getUid.
AddressMode TextureSamplerState::m_addressingMode
Referenced by getUid.
bool TextureSamplerState::m_bHwPcf
Referenced by TextureSamplerState.
TextureSamplerState::TextureSamplerState(Graphics &gfx, const TextureSamplerMode samplingMode, const FilterMode filterMode, const AddressMode addressMode)
Referenced by calcUid.
void TextureSamplerState::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
std::string TextureSamplerState::getUid() const noexcept override
std::shared_ptr< TextureSamplerState > TextureSamplerState::fetch(Graphics &gfx, const TextureSamplerMode samplingMode, const FilterMode filterMode, const AddressMode addressMode)
Referenced by ren::BlurPass::BlurPass, Cube::Cube, ren::HorizontalBlurPass::HorizontalBlurPass, ren::NegativePass::NegativePass, ren::Pass2D::Pass2D, ren::PassThrough::PassThrough, Plane::Plane, ren::ShadowPass::ShadowPass, ren::SkyPass::SkyPass, Terrain::Terrain, ren::VerticalBlurPass::VerticalBlurPass.
std::string TextureSamplerState::calcUid(const TextureSamplerMode samplingMode, const FilterMode filterMode, const AddressMode addressMode)
Referenced by getUid.
unsigned TextureSamplerState::calcSlot(const TextureSamplerMode samplingMode) noexcept
Referenced by calcUid.
unsigned TextureSamplerState::getSlot() const noexcept