BlendState
Mode
Microsoft::WRL::ComPtr<ID3D11BlendState> BlendState::m_pD3dBlendState
Referenced by BlendState, getD3dBlendState.
Mode BlendState::m_mode
Referenced by getBlendMode, getUid.
unsigned BlendState::m_renderTargetSlot
Referenced by getUid.
unsigned BlendState::m_multisampleMask
std::optional<std::array<float, 4> > BlendState::m_blendFactors
Referenced by BlendState, blendFactors, getBlendFactorAlpha, getBlendFactorBlue, getBlendFactorGreen, getBlendFactorRed, getBlendFactors, getUid.
BlendState::BlendState(Graphics &gfx, const Mode mode, const unsigned renderTargetSlot, std::optional< float > blendFactors={}, const unsigned multisampleMask=0xFFFFFFFFu)
Referenced by calcUid.
void BlendState::bind(Graphics &gfx) cond_noex override
bind graphics resource to a certain stage of the graphics pipeline
std::string BlendState::getUid() const noexcept override
void BlendState::fillBlendFactors(const float sameBlendFactor) cond_noex
void BlendState::setBlendFactors(std::array< float, 4 > blendFactors) cond_noex
void BlendState::setBlendFactorRed(const float blendFactorRed) cond_noex
void BlendState::setBlendFactorGreen(const float blendFactorGreen) cond_noex
void BlendState::setBlendFactorBlue(const float blendFactorBlue) cond_noex
void BlendState::setBlendFactorAlpha(const float blendFactorAlpha) cond_noex
float BlendState::getBlendFactorRed() const noexcept
float BlendState::getBlendFactorGreen() const noexcept
float BlendState::getBlendFactorBlue() const noexcept
float BlendState::getBlendFactorAlpha() const noexcept
const std::array< float, 4 > & BlendState::getBlendFactors() const noexcept
std::array< float, 4 > & BlendState::blendFactors()
Referenced by BlendState, calcUid, fetch.
const BlendState::Mode & BlendState::getBlendMode() const noexcept
Microsoft::WRL::ComPtr< ID3D11BlendState > & BlendState::getD3dBlendState()
std::shared_ptr< BlendState > BlendState::fetch(Graphics &gfx, const Mode mode, const unsigned renderTargetSlot, std::optional< float > blendFactors={}, const unsigned multisampleMask=0xFFFFFFFFu)
Referenced by ren::BlurPass::BlurPass, ren::NegativePass::NegativePass, ren::PassThrough::PassThrough, ren::ShadowPass::ShadowPass, ren::VerticalBlurPass::VerticalBlurPass.
std::string BlendState::calcUid(const Mode mode, const unsigned renderTargetSlot, std::optional< float > blendFactors={}, const unsigned multisampleMask=0xFFFFFFFFu)
Referenced by getUid.