ver::VertexInputLayout::ILElement
ILEementType ver::VertexInputLayout::ILElement::m_type
size_t ver::VertexInputLayout::ILElement::m_offset
size_t ver::VertexInputLayout::ILElement::getElementTypeSize(const ILEementType type) cond_noex
ver::VertexInputLayout::ILElement::ILElement(const ILEementType type, const size_t offset)
size_t ver::VertexInputLayout::ILElement::getOffsetAfterThis() const cond_noex
size_t ver::VertexInputLayout::ILElement::getOffset() const
Referenced by ver::VBElementView::getElement, ver::VBElementView::setElementByIndex.
const VertexInputLayout::ILEementType ver::VertexInputLayout::ILElement::getType() const noexcept
Referenced by ver::VBuffer::VBuffer.
const D3D11_INPUT_ELEMENT_DESC ver::VertexInputLayout::ILElement::getD3dDesc() const cond_noex
const char * ver::VertexInputLayout::ILElement::getTag() const noexcept
return a tag identifying this ILElement