IReporter
unsigned short IReporter< T >::m_notifyCounter
Referenced by IReporter< T >::notifyListeners.
std::vector<void*> IReporter< T >::m_listeners
Referenced by IReporter< T >::anyListenersPresent, IReporter< T >::hasListener, IReporter< T >::notifyListeners, IReporter< T >::numListeners, IReporter< T >::removeListener, IReporter< T >::removeThisFromListenersList.
std::vector<void*> IReporter< T >::m_listenersPendingAdd
Referenced by IReporter< T >::anyListenersPresent, IReporter< T >::hasListener, IReporter< T >::notifyListeners, IReporter< T >::numListeners, IReporter< T >::removeListener, IReporter< T >::removeThisFromListenersList, IReporter< T >::tryAddListener.
IReporter< T >::IReporter(ReporterAccess &)
virtual IReporter< T >::~IReporter() noexcept=0
bool IReporter< T >::hasListener(IListener< T > *listener) const
Referenced by IReporter< T >::tryAddListener.
void IReporter< T >::addListener(IListener< T > *listener) const
Referenced by Sandbox3d::Sandbox3d.
void IReporter< T >::removeListener(const IListener< T > *listener) const
called from ~IListener
Referenced by IListener< T >::~IListener.
void IReporter< T >::notifyListeners(const T &obj)
Referenced by IReporter< T >::notifyListeners, IReporter< T >::notifyListeners.
void IReporter< T >::notifyListeners(T &&reporter)
void IReporter< T >::notifyListeners(TArgs &&...args)
bool IReporter< T >::anyListenersPresent() const
int IReporter< T >::numListeners() const
void IReporter< T >::removeThisFromListenersList()
Referenced by ReportingNexus::~ReportingNexus.
bool IReporter< T >::tryAddListener(IListener< T > *listener) const
Referenced by IReporter< T >::addListener.