key_lua.h
bool luaCheck(lua_State *luaVm, const int ret)
Referenced by executeLuaCFunctionFromFile, executeLuaFileGetNumber, executeLuaFileGetTable, executeLuaFunctionFromFile, executeLuaGetNumber, executeLuaGetString.
void executeLuaGetNumber(lua_State *luaVm, const std::string &strVar)
Referenced by testLuaScripting.
void executeLuaGetString(lua_State *luaVm, const std::string &strVar)
Referenced by testLuaScripting.
void executeLuaFileGetNumber(lua_State *luaVm, const std::string &filename)
Referenced by testLuaScripting.
void executeLuaFileGetTable(lua_State *luaVm, const std::string &filename, const std::string &tableName)
Referenced by testLuaScripting.
void executeLuaFunctionFromFile(lua_State *luaVm, const std::string &filename, const std::string &functionName)
Referenced by testLuaScripting.
void executeLuaCFunctionFromFile(lua_State *luaVm, const std::string &filename, const std::string &luaFunctionName, const std::string &cFunctionName, TCallable f)
Referenced by testLuaScripting.
int callableFromLua_mySum(lua_State *luaVm)
C++ functions callable from Lua:
Referenced by testLuaScripting.