gph_mode
Mode
const int gph_mode::s_currentMode
Referenced by get.
static constexpr const int gph_mode::get() noexcept
you have to manually change this to switch modes (and potentially games)
Referenced by Graphics::Graphics, ren::Pass2D::Pass2D, Window::Window, Graphics::~Graphics, Window::~Window, Graphics::beginFrame, Graphics::cleanState, Window::disableCursor, Window::enableCursor, Graphics::endFrame, Window::windowProcDelegate, wWinMain.