util
auto util::s_XMZero
float util::PI
Referenced by Camera::getShadowProjectionMatrix, Geometry::makeSphereTesselated, Camera::rotateRel, toDegrees, toRadians.
double util::PI_D
Referenced by gaussian1d, gaussian2d, gaussianFilter, wrapAngle.
T util::Epsilon
Referenced by isApproximatelyEqual, isNormalized.
HANDLE util::g_hThreadQuitcEvent
Referenced by setupDetachedThreadsVector, terminateDetachedThreads.
std::vector<HANDLE> util::g_detachedThreads
Referenced by setupDetachedThreadsVector, terminateDetachedThreads.
void util::comSafeRelease(T &p)
safely release a COM object deprecated
Referenced by queryRefreshRate.
bool util::isNormalized(const DirectX::XMFLOAT3 &vec)
Referenced by Camera::computePitchYawInDegFromDirectionVector.
DirectX::XMMATRIX XM_CALLCONV util::computeTransform(const DirectX::XMFLOAT3 &scale, const DirectX::XMFLOAT3 &pos, const DirectX::XMFLOAT3 &rot)
DirectX::XMFLOAT3 util::extractRotation(const DirectX::XMFLOAT4X4 &mat)
builds a FLOAT3 of {x=pitch,y=yaw,z=roll}
util::ALIAS_FUNCTION(extractRotation, extractEulerAngles)
float util::getPitch(const DirectX::XMFLOAT4X4 &mat)
float util::getYaw(const DirectX::XMFLOAT4X4 &mat)
float util::getRoll(const DirectX::XMFLOAT4X4 &mat)
bool util::operator==(const DirectX::XMFLOAT3 &lhs, const DirectX::XMFLOAT3 &rhs) noexcept
bool util::operator!=(const DirectX::XMFLOAT3 &lhs, const DirectX::XMFLOAT3 &rhs) noexcept
bool util::operator==(const DirectX::XMFLOAT4 &lhs, const DirectX::XMFLOAT4 &rhs) noexcept
bool util::operator!=(const DirectX::XMFLOAT4 &lhs, const DirectX::XMFLOAT4 &rhs) noexcept
bool util::operator==(const DirectX::XMVECTOR &lhs, const DirectX::XMVECTOR &rhs) noexcept
bool util::operator!=(const DirectX::XMVECTOR &lhs, const DirectX::XMVECTOR &rhs) noexcept
bool util::operator==(const DirectX::XMMATRIX &lhs, const DirectX::XMMATRIX &rhs) noexcept
bool util::operator!=(const DirectX::XMMATRIX &lhs, const DirectX::XMMATRIX &rhs) noexcept
DirectX::XMFLOAT3 util::extractTranslation(const DirectX::XMFLOAT4X4 &mat)
Referenced by testScaleMatrixTranslation.
DirectX::XMFLOAT3 util::extractTranslationColumnMatrix(const DirectX::XMFLOAT4X4 &mat)
DirectX::XMMATRIX XM_CALLCONV util::scaleTranslation(const DirectX::XMMATRIX &mat, const float scale)
Referenced by Model::Model, Model::parseModelNodeGraph, testScaleMatrixTranslation.
DirectX::XMVECTOR XM_CALLCONV util::pitchYawRollToQuaternion(const DirectX::XMVECTOR &pitchYawRollAnglesVec)
Referenced by Node::getRotationQuat, Node::updateLocalTransform.
DirectX::XMVECTOR XM_CALLCONV util::pitchYawRollToQuaternion(const DirectX::XMFLOAT3 &pitchYawRollAngles)
util::ALIAS_FUNCTION(pitchYawRollToQuaternion, eulerAnglesToQuaternion)
void util::quaternionToEulerAngles(const DirectX::XMFLOAT4 &quat, float &pitch, float &yaw, float &roll)
Referenced by decomposeAffineMatrix, Node::setTransform, Node::setTransform.
DirectX::XMFLOAT3 util::quaternionToEulerAngles(const DirectX::XMFLOAT4 &quat)
std::tuple< DirectX::XMFLOAT3, DirectX::XMFLOAT3, DirectX::XMFLOAT3 > util::decomposeAffineMatrix(const DirectX::XMFLOAT4X4 &transform)
Referenced by Node::Node, decomposeAffineMatrix.
std::tuple< DirectX::XMFLOAT3, DirectX::XMFLOAT3, DirectX::XMFLOAT3 > util::decomposeAffineMatrix(const DirectX::XMMATRIX &transform)
void util::toDegrees3InPlace(DirectX::XMFLOAT3 &rotAngles)
DirectX::XMFLOAT3 util::toDegrees3(const DirectX::XMFLOAT3 &rotAngles)
Referenced by DirectionalLight::displayImguiWidgets.
void util::toRadians3InPlace(DirectX::XMFLOAT3 &rotAngles)
DirectX::XMFLOAT3 util::toRadians3(const DirectX::XMFLOAT3 &rotAngles)
Referenced by ILightSource::ILightSource, Model::Model, DirectionalLight::displayImguiWidgets.
DirectX::XMFLOAT3 util::quaternionToPitchYawRoll(DirectX::XMFLOAT4 &quat)
same as quaternionToEulerAngles except this version returns the euler angles in a float3 vector
dx::XMVECTOR XM_CALLCONV util::pitchYawRollToVector(const float pitch, const float yaw, const float roll)
float util::distance(const DirectX::XMFLOAT3 &v1, const DirectX::XMFLOAT3 &v2) noexcept
Referenced by distance, Mesh::getDistanceFromActiveCamera, Mesh::setDistanceFromActiveCamera.
util::ALIAS_FUNCTION(distance, length)
float util::distanceSquared(const DirectX::XMFLOAT3 &v1, const DirectX::XMFLOAT3 &v2) noexcept
Referenced by distanceSquared.
util::ALIAS_FUNCTION(distanceSquared, lengthSquared)
DirectX::XMVECTOR XM_CALLCONV util::addVectorWithScalar(const DirectX::XMVECTOR &v, const float scalar) noexcept
DirectX::XMVECTOR XM_CALLCONV util::subtractScalarFromVector(const DirectX::XMVECTOR &v, const float scalar) noexcept
DirectX::XMVECTOR XM_CALLCONV util::multiplyVectorWithScalar(const DirectX::XMVECTOR &v, const float scalar) noexcept
DirectX::XMVECTOR XM_CALLCONV util::divideVectorWithScalar(const DirectX::XMVECTOR &v, const float scalar) noexcept
DirectX::XMFLOAT3 util::getMidpointOfTriangle(const DirectX::XMFLOAT3 &v0, const DirectX::XMFLOAT3 &v1, const DirectX::XMFLOAT3 &v2) noexcept
DirectX::XMVECTOR util::rotateVectorAroundAxisAngle(const DirectX::XMVECTOR &v, const DirectX::XMVECTOR &axis, const float theta) noexcept
rotate a vector around an axis and an angle (in degrees) using Rodrigues' rotation formula:
axis * cos( theta ) + ( axis.Dot( v ) * v * ( 1 -cos( theta ) ) + ( v.Cross( axis ) * sin( theta ) );
DXGI_RATIONAL util::queryRefreshRate(const unsigned screenWidth, const unsigned screenHeight, const bool bVsync)
static TShader * util::createShaderObject(ID3D11Device *pD3dDevice, ID3DBlob *&pShaderBlob, ID3D11ClassLinkage *pClassLinkage)
static ID3D11VertexShader * util::createShaderObject< ID3D11VertexShader >(ID3D11Device *pD3dDevice, ID3DBlob *&pShaderBlob, ID3D11ClassLinkage *pClassLinkage)
static ID3D11PixelShader * util::createShaderObject< ID3D11PixelShader >(ID3D11Device *pD3dDevice, ID3DBlob *&pShaderBlob, ID3D11ClassLinkage *pClassLinkage)
TShader * util::loadShaderDynamically(ID3D11Device *pD3dDevice, const std::wstring &fileName, const std::string &entryPoint, const std::string &profile, ID3DBlob *&pShaderBlob, const std::vector< D3D_SHADER_MACRO > &defines={})
will be used to load and compile a shader at runtime
util::ALIAS_FUNCTION(loadShaderDynamically, compileShaderDynamically)
std::optional< DirectX::XMVECTORF32 > util::getDirectXColorFromString(const std::string &dxColorString)
Referenced by gui::Component::Component_State::Component_State.
bool util::displayFileInfo(const std::filesystem::path &targetPath)
Referenced by displayDirTree.
void util::displayDirTree(const std::filesystem::path &targetPath, int level)
Referenced by displayDirTree.
size_t util::getFileSize(const std::filesystem::path &pathToCheck)
bool util::displayTextFile(const std::filesystem::path &targetPath)
bool util::displayBinaryFile(const std::filesystem::path &targetPath)
void util::writeFile(const std::filesystem::path &path, const std::string &data)
void util::deleteFile(const std::string &filename)
void util::searchFile(const std::filesystem::path &directory, const std::filesystem::path &filename)
bool util::createDirectory(const std::string &str)
void util::setFilePermissions(const std::string &path, std::filesystem::perms permsToSet, std::filesystem::perm_options permsAction)
std::string util::getFilename(const std::string &path)
Referenced by Model::Model.
std::string util::getFileExtension(const std::string &filename)
Referenced by Bitmap::save.
bool util::isFileBinary(const char *fname)
read 255 chars just to be sure
size_t util::countLinesOfFile(const char *fileName)
count lines of a file
size_t util::countColumnsOfFile(const char *fileName)
calculate columns of a file (assuming that the file has equal ammount of columns - maximum ammount of columns in any given line)
T util::abs(const T val)
Referenced by getFractionalPart, isNormalized, squareRoot, truncate.
int util::truncate(const T val)
truncate the supplied number val; handles negative numbers as well
T util::modulus(const T divident, const T divisor) noexcept
'fmod()' === '' : returns the signed floating point remainder of a division (divident / divisor)
Referenced by ceil, floor.
int util::ceil(const T val) noexcept
Referenced by Terrain::Terrain, gaussianFilter.
int util::floor(const T val) noexcept
Referenced by Geometry::makePlanarGridTexturedFromHeighmap, mapToByte, mapToByte, numberToCoord, round.
int util::round(const T val) noexcept
Referenced by Graphics::Graphics, getFractionalPartAsInt, mapRangeRounded.
T util::powerOf(T x, J n)
calculate x^n, n > 1
Referenced by cosine, getFractionalPartAsInt, isPrime, sine.
T util::getFractionalPart(T val)
works like std::modf which decomposes given floating point value num into integral and fractional parts
std::uint64_t util::getFractionalPartAsInt(const T val, const int numberOfDecimalPlaces)
T util::clamp(T number, T minimum, T maximum)
Referenced by SettingsManager::loadFromFile, numberToCoord.
int util::numberToCoord(T number, int amountPerGradation, int nGradations, bool is_x_axis)
transformation of a scalar (1D) to a Cartesian coordinate
T util::mapRangeRounded(const T val, const T inFirst, const T inLast, const T outFirst, const T outLast) noexcept
T util::mapRange(const T val, const T inFirst, const T inLast, const T outFirst, const T outLast) noexcept
bool util::isApproximatelyEqual(const T x, const T y)
checks for approximate equality between floating point numbers
T util::mult10(const T num)
T util::div10(const T dividend)
T util::squareRoot(const T x) noexcept
calculates the square root of a number
Referenced by quadratic.
void util::quadratic(const T a, const T b, const T c)
T util::square(const T x)
Referenced by gaussian1d, gaussian2d, gaussianFilter.
std::string util::toHexString(const T i)
Referenced by Window::WindowClass::WindowClass.
T util::normalizeTo01(const T val, const T min, const T max)
T util::convertRange(const T valueInRange, const T oldMin, const T oldMax, const T newMin, const T newMax)
T util::wrapAngle(const T angleRad)
wrap angle (in radians) in the range -pi to pi
Referenced by Camera::rotateRel.
T util::toRadians(const T deg)
convert angle in degrees to radians
Referenced by Camera::computeTargetVector, rotateVectorAroundAxisAngle.
T util::toDegrees(const T rad)
convert angle in radians to degrees
Referenced by Camera::computePitchYawInDegFromDirectionVector.
void util::normalizeAngleDeg(float &angleDeg)
Referenced by isAngleDegWithinRange.
bool util::isAngleDegWithinRange(float angleDeg, float a, float b)
T util::interpolate(const T &src, const T &dst, const double alpha)
linear interpolation from src to dst value using alpha provided, interpolates any two Types that support the operations +, -, *
util::ALIAS_FUNCTION(interpolate, lerp)
T util::gaussian1d(const T x, const T sigma, const T mean=(T) 0) noexcept
1d Gaussian distribution
<image url="C:/Users/nikla/pictures/gaussian function distribution.png" scale=".4" >
Referenced by ren::Renderer3d::setKernelGauss.
T util::gaussian2d(const T x, const T y, const T sigma) noexcept
Isotropic (mean = 0) 2d Gaussian distribution.
T util::gaussianFilter(const T x, const T y, const int kernelSize=5) noexcept
Isotropic (mean = 0) 2d Gaussian distribution.
T util::randomInRange(const T start, const T end)
int util::signum(const T val)
T util::nthMultipleOf(const T number, const int n)
int util::nextPowerOf2(int n)
find smallest power of 2 greater than or equal to n
int util::gcd(int divident, int divisor)
prints Greatest Common Divisor of numbers
int util::factorialOf(int n) noexcept
Referenced by cosine, sine.
bool util::isPrime(const int number) noexcept
trial division method
size_t util::computeTriangularNumber(const int number) noexcept
Triangular numbers represent the number of dots that can form an equilateral triangle.
bool util::isPowerOfTwo(const std::size_t value) noexcept
float util::cosine(float x) noexcept
float util::sine(float x) noexcept
int util::linearSearch(const int *A, const int n, const int x)
int util::binarySearch(const int *A, int low, int high, const int x)
int util::toDecimal(const int hex)
int util::toHex(const int dec)
void util::printDec2Bin(const size_t size, void const *const ptr) noexcept
prints given datatype to binary
bitwise ops
void util::printDecToBin(const int num) noexcept
print binary conversion of supplied decimal number
bool util::haveOppositeSigns(int x, int y) noexcept
int util::msbIndexOfDec(int num) noexcept
finds MSB index in decimal number (counting from 0)
int util::countSetBits(int num) noexcept
count number of Ones in a given number
int util::isPowerOf2(const int num) noexcept
checks whether a number is a power of 2
Referenced by isSetByNumber.
void util::convertToBase(int number, const int base) noexcept
bool util::isNthBitSet(const int value, const int posOfTestBit)
int util::swapBits(int num, const int i, const int j) noexcept
swap the bits at position i and j of given number iff they are different
int util::setNthBit(int num, const unsigned n) noexcept
int util::clearNthBit(int num, const unsigned n) noexcept
int util::toggleNthBit(int num, const unsigned n) noexcept
int util::isSet(int num, const unsigned bitPos) noexcept
check num's bitPos state and return the value (0 or 1)
bool util::isSetByNumber(int num, int bitFlag) noexcept
check if num has bit indicated by bitFlag set. bitFlag must be a power of 2.
Referenced by Graphics::bindBackBufferAsInput.
int util::changeNthBit(int num, const unsigned n, const bool bitVal) noexcept
change nth bit to bitVal
std::string util::printHresultErrorDescription(const HRESULT hres)
print HRESULT errors in understandable English
std::wstring util::printHresultErrorDescriptionW(const HRESULT hres)
Referenced by KeyConsole::KeyConsole, KeyConsole::setColor, KeyConsole::setDefaultColor.
std::string util::getLastErrorAsString()
Returns the last Win32 error, in string format.
std::string util::getLastNtErrorAsString(const DWORD ntStatusCode)
std::wstring util::bstrToStr(const BSTR &bstr)
BSTR util::strToBstr(const std::wstring &str)
__int64 util::filetimeToInt64(const FILETIME &fileTime)
DWORD_PTR util::pinThreadToCore(const HANDLE hThread, const DWORD core)
returns the thread's previous affinity mask
void util::setCurrentThreadName(const std::string &name)
std::string util::getKnownFolderPath(const int id=CSIDL_PERSONAL)
void util::setupDetachedThreadsVector(const unsigned nThreads)
void util::terminateDetachedThreads()
std::optional< DWORD > util::registryGetDword(const HKEY hKey, const std::wstring &regName)
std::optional< std::wstring > util::registryGetString(const HKEY hKey, const std::wstring &regName)
static void util::suspendAllThreads()
void util::launchProcess(const std::string &path)
decltype(auto) util::askForCredentials(TCallback &&f, TArgs &&... args)
uint64_t util::combineUnsignedInt32to64(const unsigned int high32Bit, const unsigned int low32Bit)
void util::safeDelete(T *&p)
void util::safeDelete(T &pSm)
T util::sum(std::initializer_list< T > lst)
bool util::isFutureReady(const std::future< T > &fu)
std::vector< std::string > util::tokenizeQuotedString(const std::string &input)
converts a string input into a vector of strings
separation into vector element "tokens" is based on spaces or quotes '
std::wstring util::s2ws(const std::string &narrow)
convert from strings/chars to wide strings/wchar_ts, or std::wstring( s.begin(), s.end() );
Referenced by KeyConsole::KeyConsole, PixelShader::PixelShader, Sound::Sound, VertexShader::VertexShader, Window::Window, Window::WindowClass::WindowClass, Window::WindowClass::~WindowClass, Window::displayMessageBoxOkCancel, Window::displayMessageBoxYesNo, finally, KeyConsole::getWindowHandle, launchProcess, Bitmap::loadFromFile, SettingsManager::loadFromFile, gui::UIPass::recreate, Bitmap::save, KeyConsole::setFont, Window::setFont, KeyConsole::setTitle, Window::setTitle, wWinMain.
std::string util::ws2s(const std::wstring &wide)
convert wide strings/wchar_ts to strings/chars
Referenced by Window::Window, finally, getKnownFolderPath, KeyConsole::getTitle, Graphics::Adapter::getVRamDetails, printHresultErrorDescription.
void util::removeSubstring(std::string &str, const std::string &substring)
std::string util::trimStringFromStart(const std::string &str, const int nChars)
trim nChars from the start of the string
Referenced by Mesh::getName.
std::string util::trimStringFromEnd(const std::string &str, const int nChars)
void util::trimStringFromStartInPlace(std ::string &str, const int nChars)
void util::trimStringFromEndInPlace(std::string &str, const int nChars)
std::vector< std::string > util::splitDelimitedString(const std::string &str, const char delimiter)
example: splitDelimitedString( sea_horde_faction_keys, ";" );
std::string util::assembleDelimitedString(const std::vector< std::string > &delimitedString, const char delimiter)
void util::removeFromDelimitedString(std::vector< std::string > &delimitedString, const char delimiter, const std::string &str)
removes all occurrences of str from delimited_string
bool util::stringContains(std::string_view haystack, std::string_view needle)
std::string & util::capitalizeFirstLetter(std::string &str)
Referenced by ImguiConstantBufferVisitorShowcase::onSetMaterial.
std::string util::capitalizeFirstLetter(const std::string &str)
std::string util::intToStr(int integer) noexcept
int util::stringToInt(const std::string &str) noexcept
void util::trimSpacesLeft(std::string &s)
trimSpaces from start (in place)
Referenced by trimSpaces, trimSpacesLCopy.
void util::trimSpacesRight(std::string &s)
trimSpaces from end (in place)
Referenced by trimSpaces, trimSpacesRightCopy.
void util::trimSpaces(std::string &s)
trimSpaces from both ends (in place)
Referenced by trimSpacesCopy.
std::string util::trimSpacesCopy(std::string s)
trimSpaces from both ends (copying)
std::string util::trimSpacesLCopy(std::string s)
trimSpaces from start (copying)
std::string util::trimSpacesRightCopy(std::string s)
trimSpaces from end (copying)
std::string util::toString(const T &t)
void util::printBinary(const T val)
std::tuple< int, int, int > util::timeToHms(const float time)
std::tuple< int, int, int > util::secondsToHms(const int totalSecs)
time_t util::secondsToTimeT(const int s)
convert seconds to time_t
Although not defined, time_t is implementation defined, it is almost always an integral value holding the number of seconds (not counting leap seconds) since 00:00, Jan 1 1970 UTC, corresponding to POSIX time.
long int util::timeTtoSeconds(const time_t t)
convert time_t to seconds time_t can be acquired as if by means of time(nullptr)
Referenced by PerlinNoise::PerlinNoise.
std::uintptr_t util::pointerToInt(const void *p)
Referenced by addPointers, Texture::calcUid.
void * util::intToPointer(const uintptr_t i)
Referenced by addPointers.
void * util::addPointers(const void *p1, const void *p2)
std::string util::operator+(const std::string_view &sv1, const std::string_view &sv2)
std::string util::getNumberString(const T num)
print a comma every 3 decimal places
std::string util::generateCaptcha(int len)
unsigned char util::mapToByte(const float value)
Referenced by BmpLoader::generateData.
unsigned char util::mapToByte(const double value)
bool util::isAligned(const volatile void *p, const std::size_t alignment) noexcept
check whether the address is aligned to alignment boundary
Referenced by alignPtr.
bool util::isAligned(const std::uintptr_t pi, const std::size_t alignment) noexcept
const int util::is4ByteAligned(const intptr_t *addr)
T * util::alignForward(const T *p, const std::size_t alignment) noexcept
align pointer forward with given alignment
std::uintptr_t util::alignForward(const std::uintptr_t ip, const std::size_t alignment) noexcept
std::size_t util::calcAlignedSize(const std::size_t size, const std::size_t alignment)
calculates alignment in bits supposedly
std::size_t util::getForwardPadding(const std::size_t p, const std::size_t alignment)
calculate padding bytes needed to align address p forward given the alignment
Referenced by getForwardPaddingWithHeader.
std::size_t util::getForwardPaddingWithHeader(const std::size_t p, const std::size_t alignment, const std::size_t headerSize)
T * util::alignPtr(const T *ptr, const std::size_t alignment)
unsigned int volatile & util::readMEM(unsigned int memoryAddress)
unsigned long long int volatile & util::readMEM(unsigned long long int memoryAddress)
restricted noaliasing void * util::getUniqueMemory(const std::size_t bytes)
if you allocate an object on the heap, it will be given a unique address within that process; nothing else will be assigned that address until you free the object
T & util::deconst(const T &obj)
T * util::deconst(const T *obj)
decltype(auto) util::pointerToIterator(TContainer &c, TP pElem)
Referenced by removeByBackSwap.
void util::removeByBackSwap(TContainer &container, typename TContainer::size_type index)
Referenced by gui::Component::~Component, gui::Component::set_enable_top_most.
void util::removeByBackSwap(TContainer &container, typename TContainer::iterator iter)
void util::removeByBackSwap(std::vector< T, Alloc > &v, T p)
void util::removeByBackSwap(TContainer &c, Predicate pred)
void util::shrinkCapacity(std::vector< T, Alloc > &v)
shrink vector's capacity to its size
void util::moveIf(InputIt srcFirst, InputIt srcLast, OutputIt *destFirst, TPredicate predicate)
note that there is std::move(inIt1, inIt2, outIt);
void util::splitMovePartition(Container &src, Container &dest, TPredicate p)
like partition_move - puts the second group of an std::partition to another container removing them from the source container
void util::printContainer(const TContainer &cont, const char *delimiter=" ")
void util::regexSearch(const std::regex &pattern)
decltype(auto) util::doForAll(TContainer &c, Func f)
Referenced by gui::Component::set_user_property.
decltype(auto) util::filterContainer(Container &c, const FilterFunction &&f)
TContainer::iterator util::erase(TContainer &container, typename TContainer::const_reference element_to_erase)
TContainer::iterator util::eraseIf(TContainer &container, TPredicate &&predicate)
bool util::containerContains(const TContainer &container, const T &val)
Referenced by insertUnique.
bool util::atLeastNOfRange(TIt begin, TIt end, size_t n, TPredicate &&predicate)
test if at least N elements of an iterator range match a predicate
earlies out and returns once the required amount of elements have been matched
Referenced by atLeastNOfRange.
bool util::atLeastNOfRange(const TContainer &container, size_t n, TPredicate &&predicate)
unsigned util::indexOf(const TContainer &container, const T &val)
bool util::insertUnique(const TContainer &container, T &&val, TInserter &&inserter)
util::ALIAS_FUNCTION(insertUnique, emplaceBackUnique)
TContainer::iterator util::insertUniqueAndReturnIt(TContainer &container, TPredicate &&predicate, TArgs &&... args)
util::ALIAS_FUNCTION(insertUniqueAndReturnIt, emplaceBackUniqueAndReturnIt)
bool util::hasDuplicates(const TContainer &container, const TComparator &comparator)
Referenced by hasDuplicates.
bool util::hasDuplicates(const TContainer &container)
std::set< typename TContainer::value_type > util::uniquefy(const TContainer &container)
dx::XMFLOAT3 util::extractRotation(const dx::XMFLOAT4X4 &mat)
float util::getPitch(const dx::XMFLOAT4X4 &mat)
float util::getYaw(const dx::XMFLOAT4X4 &mat)
float util::getRoll(const dx::XMFLOAT4X4 &mat)
dx::XMFLOAT3 util::extractTranslation(const dx::XMFLOAT4X4 &mat)
dx::XMFLOAT3 util::extractTranslationColumnMatrix(const dx::XMFLOAT4X4 &mat)
dx::XMMATRIX XM_CALLCONV util::scaleTranslation(const dx::XMMATRIX &mat, const float scale)
dx::XMVECTOR XM_CALLCONV util::pitchYawRollToQuaternion(const dx::XMVECTOR &pitchYawRollAnglesVec)
dx::XMVECTOR XM_CALLCONV util::pitchYawRollToQuaternion(const dx::XMFLOAT3 &pitchYawRollAngles)
DirectX::XMFLOAT3 util::quaternionToPitchYawRoll(dx::XMFLOAT4 &quat)
bool util::displayFileInfo(const fs::path &targetPath)
void util::displayDirTree(const fs::path &targetPath, int level)
size_t util::getFileSize(const fs::path &pathToCheck)
bool util::displayTextFile(const fs::path &targetPath)
bool util::displayBinaryFile(const fs::path &targetPath)
void util::writeFile(const fs::path &path, const std::string &data)
void util::searchFile(const fs::path &directory, const fs::path &filename)
void util::setFilePermissions(const std::string &path, fs::perms permsToSet, fs::perm_options permsAction)
static void util::suspendAllThreads()