Geometry
TriangleMesh Geometry::makeLine(const float length=1.0f/2.0f, std::optional< ver::VertexInputLayout > layout={})
Referenced by Line::Line.
TriangleMesh Geometry::makeCube(std::optional< ver::VertexInputLayout > layout={}, const float side=1.0f/2.0f)
Referenced by ren::SkyPass::SkyPass.
TriangleMesh Geometry::makeCubeIndependentFaces(ver::VertexInputLayout layout, const float side=1.0f/2.0f)
Referenced by makeCubeIndependentFacesTextured.
TriangleMesh Geometry::makeCubeIndependentFacesTextured()
Referenced by Cube::Cube.
TriangleMesh Geometry::makeSphereTesselated(std::optional< ver::VertexInputLayout > layout=std::nullopt, const unsigned nLateralDivs=12, const unsigned nLongitudinalDivs=24, const float radius=1.0f)
Referenced by ren::SkyPass::SkyPass, Sphere::Sphere.
TriangleMesh Geometry::makePlanarGrid(const int length=2, const int width=2, int nDivisionsX=1, int nDivisionsY=1)
nDivisionsX are length divisions
TriangleMesh Geometry::makePlanarGridTextured(const int length=2, const int width=2, int nDivisionsX=1, int nDivisionsY=1)
Referenced by Plane::Plane, Terrain::Terrain.
TriangleMesh Geometry::makePlanarGridTexturedFromHeighmap(const std::string &filename, const int normalizeAmount=4, const int terrainAreaUnitMultiplier=10, const int length=2, const int width=2, int nDivisionsX=1, int nDivisionsY=1)
engine unit is cm, terrain has to be relatively large without consuming a vast amount of memory with indices and vertices, so we multiply its area by terrainAreaUnitMultiplier
Referenced by Terrain::Terrain.
TriangleMesh Geometry::makeCameraFrustum(const float width, const float height, const float nearZ, const float farZ)
Referenced by CameraFrustum::CameraFrustum, Camera::updateCameraFrustum.
TriangleMesh Geometry::makeCameraWidget()
Referenced by CameraWidget::CameraWidget.