texture_desc.h
BindFlags
CpuAccessFlags
TextureUsage
RenderTargetViewMode
DepthStencilViewMode
MultisamplingMode
const D3D11_TEXTURE2D_DESC createTextureDescriptor(const unsigned width, const unsigned height, const DXGI_FORMAT format, const BindFlags bindFlags, const CpuAccessFlags cpuAccessFlags, const TextureUsage usage, const bool bCube, const unsigned nTextures=1u, const MultisamplingMode multisamplingMode=MultisamplingMode::None)
Referenced by CubeTexture::CubeTexture, CubeTextureArrayOffscreenDS::CubeTextureArrayOffscreenDS, CubeTextureOffscreenDS::CubeTextureOffscreenDS, CubeTextureOffscreenRT::CubeTextureOffscreenRT, IDepthStencilView::IDepthStencilView, IRenderTargetView::IRenderTargetView, Texture::Texture, Texture::Texture, TextureArrayOffscreenDS::TextureArrayOffscreenDS, TextureOffscreenDS::TextureOffscreenDS, TextureOffscreenRT::TextureOffscreenRT, IDepthStencilView::createStagingTexture, IRenderTargetView::createStagingTexture.
const DXGI_FORMAT getFormatRtv(const RenderTargetViewMode mode)
Referenced by RenderTargetShaderInput::RenderTargetShaderInput, TextureOffscreenRT::TextureOffscreenRT.
const DXGI_FORMAT getTypelessFormatDsv(const DepthStencilViewMode mode)
Use when creating the texture descriptor.
DS format for D3D11_TEXTURE2D_DESC creation _TYPELESS is actually a float type DXGI_FORMAT_R32_TYPELESS is compatible with both DXGI_FORMAT_D32_FLOAT and DXGI_FORMAT_R32_FLOAT typeless formats that allow the same texture to be interpreted differently depending on the context and they are necessary if the texture is to be used in multiple contexts eg. depth testing and sampling in shaders
Referenced by CubeTextureArrayOffscreenDS::CubeTextureArrayOffscreenDS, CubeTextureOffscreenDS::CubeTextureOffscreenDS, IDepthStencilView::IDepthStencilView, TextureArrayOffscreenDS::TextureArrayOffscreenDS, TextureOffscreenDS::TextureOffscreenDS.
const DXGI_FORMAT getTypedFormatDsv(const DepthStencilViewMode mode)
when we want to map a texture view on the Depth Stencil
Referenced by IDepthStencilView::IDepthStencilView, IDepthStencilView::IDepthStencilView, IDepthStencilView::IDepthStencilView.
const DXGI_FORMAT getShaderInputFormatDsv(const DepthStencilViewMode mode)
when we want to sample from the Depth Stencil in the back buffer
Referenced by CubeTextureArrayOffscreenDS::CubeTextureArrayOffscreenDS, CubeTextureOffscreenDS::CubeTextureOffscreenDS, DepthStencilShaderInput::DepthStencilShaderInput, TextureArrayOffscreenDS::TextureArrayOffscreenDS, TextureOffscreenDS::TextureOffscreenDS.